### ISSUE TITLE
Fails on XAU2511

### ISSUE THREAD

**Issue by netadair** [jclehner/nmrpflash#1]
Hello!
I'm glad I found this tool, which looks (looked :( ) very promising.
However it fails on a bricked XAU2511 device.
I connected the console, and pressing the reset button for a while (10sec+), the process started. 
However as soon as nmrpflash starts to try to upload, the device either stops downloading and resets, or when keeping the reset button pressed, complains in an endless loop (until nmrpflash timeout) about

[...]
NMRP client Configuring Request send
NMRP Config Ack received
NMRP set tftp-server IP success
No DEV-REGION option (-> here, maybe it expects CE which is the current region?!)
Recv FW-UP options
No ST-UP option
timeouts..Back to tftp waiting state.
[...]

Any idea?

Best regards
Michael

**Comment by netadair** [comment]
PS:
After checking the log file, in one single case I even found an upload:

send TFTP_UL_REQ with [firmware]
##sending NMRP_CODE_TFTP_UL_REQ again...
##sending NMRP_CODE_TFTP_UL_REQ again...
##sending NMRP_CODE_TFTP_UL_REQ again...


**TFTP Client Upload, File Name: firmware

**TFTP Client Upload File Size = 49F Bytes at 80500000

Success!
<XAU2511>#TFTP got FW, Chking img...

Image faile

[and then the loop]

49F bytes is a bit short, right?

**Comment by jclehner** [comment]
Please re-run `nmrpflash` with `-vvv` and post the output, plus all the arguments used to call it. `0x49f` can't possibly be the size of of the firmware file. I suspect that there is a bug in the TFTP upload code...

**Comment by jclehner** [comment]
Need more info; closing for now.

**Comment by jclehner** [comment]
Issue should be fixed in v0.9.5!
