### ISSUE TITLE
Success on Netgear R6220

### ISSUE THREAD

**Issue by sabrylk** [jclehner/nmrpflash#100]
Just to let you know was able to successfully debrick my R6220 router. Found that nmrpflash is easier than trying to use tftp. Thanks again. Documented the steps I followed [https://github.com/sabrylk/guides/blob/main/Netgear-R6220-Debrick/README.md](url)

**Comment by Stavinair** [comment]
bad link

**Comment by sabrylk** [comment]
Corrected the link
