### ISSUE TITLE
Not an issue-why use nmrpflash over tftp?

### ISSUE THREAD

**Issue by whateverusernameisnottaken** [jclehner/nmrpflash#101]
Hi:

I'm not meaning to sound sarcastic, it's just an honest question. Why use nmrpflash over just tftp? As I understand it, nmrpflash can recover/flash routers that are just not responding to tftp. Is that correct?

If so, what symptoms/conditions on a router indicate that you should use nmrpflash?

I'm just wanting to learn.

Thanks

**Comment by jclehner** [comment]
If your device is in a state where TFTP is enabled anyways, then there's no benefit in using `nmrpflash`. There are however devices or situations, where the bootloader won't allow TFTP uploads without going through NMRP.

In short, if TFTP is inaccessible, try `nmrpflash`.

**Comment by jclehner** [comment]
A bootloop is actually one of the cases where it's possible that normal TFTP recovery won't be available, while `nmrpflash` will. Unless of course the firmware crashes because of a hardware error.
