### ISSUE TITLE
problem regarding a full reset,

### ISSUE THREAD

**Issue by FrostKnight** [jclehner/nmrpflash#102]
nmrpflash, still works in a reset, but with one glaring exception,
I don't suppose you know, how to reset the router, so that the password also is completely reset as well?

Odd thing is, I tried using nmrpflash for this, as well as, the reset button on it, but I think the backup that is currently in the system, keeps resetting it to its previous state before I bricked it.

Aka, I forgot my password and have an issue due to this.

Think I typed it wrong somehow.

Not that this is required, but if possible, a factory reset feature, might be appreciated as well, even if it is in an advanced options part of manpages or w/e...

With obvious warnings for sure.

Same router as I used before btw...

**Comment by jclehner** [comment]
> Not that this is required, but if possible, a factory reset feature, might be appreciated as well, even if it is in an advanced options part of manpages or w/e...

The NMRP protocol has no factory reset method, so it's not possible to implement such a feature in `nmrpflash`.
