### ISSUE TITLE
Unable to compile source after opening with codeblocks

### ISSUE THREAD

**Issue by discmon** [jclehner/nmrpflash#103]
Hey, I am trying to modify your code to fix some errors, however, I am unable to compile the code following your instructions on Windows.
I have cloned your entire github, and placed the newest version of the npcap sdk into the root folder.
After looking at codeblocks build properties (involving the linker and library location), I renamed the folder containing npcap sdk to "Npcap" to match your linkers.

However, when compiling the code, I am shown the following errors:
||=== Build: default in nmrpflash (compiler: GNU GCC Compiler) ===|
ld.exe||cannot find -liphlpapi: No such file or directory|
ld.exe||cannot find -lws2_32: No such file or directory|
ld.exe||cannot find -ladvapi32: No such file or directory|
ld.exe||cannot find -lmingw32: No such file or directory|
ld.exe||cannot find -lgcc: No such file or directory|
ld.exe||cannot find -lgcc_eh: No such file or directory|
ld.exe||cannot find -lmoldname: No such file or directory|
ld.exe||cannot find -lmingwex: No such file or directory|
ld.exe||cannot find -lmsvcrt: No such file or directory|
ld.exe||cannot find -lkernel32: No such file or directory|
ld.exe||cannot find -lpthread: No such file or directory|
ld.exe||cannot find -ladvapi32: No such file or directory|
ld.exe||cannot find -lshell32: No such file or directory|
ld.exe||cannot find -luser32: No such file or directory|
ld.exe||cannot find -lkernel32: No such file or directory|
ld.exe||cannot find -lmingw32: No such file or directory|
ld.exe||cannot find -lgcc: No such file or directory|
ld.exe||cannot find -lgcc_eh: No such file or directory|
ld.exe||cannot find -lmoldname: No such file or directory|
ld.exe||cannot find -lmingwex: No such file or directory|
ld.exe||cannot find -lmsvcrt: No such file or directory|
ld.exe||cannot find -lkernel32: No such file or directory|
||error: ld returned 1 exit status|
||=== Build failed: 23 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|

Could you please advice on how you manage to compile the code on Codeblocks?
Thanks.

**Comment by jclehner** [comment]
You're probably compiling the code with a 64-bit toolchain, while the project is set up for a 32-bit build.

**Comment by discmon** [comment]
Thanks for the info. Managed to get it working with the 32 bit tool chain.
Documentation:
Download the MSYS installer for mingw and follow the instructions there to install the 64 bit tool chain, then execute this command to install the 32bit toolchain pacman -S --needed mingw-w64-i686-toolchain
After that is done, go into codeblocks, then select settings >> Compiler...
Go to Toolchain executables and change the compiler's installation directory to 
C:\msys64\mingw32 for it to use the 32bit tool chain instead
