### ISSUE TITLE
failed to set hardware filter to promiscuous mode

### ISSUE THREAD

**Issue by green1052** [jclehner/nmrpflash#104]
```
\Device\NPF_{FBA526AC-1FB5-42E5-ACA9-D20F6F593233}: failed to set hardware filter to promiscuous mode: 시스템에 부착된  장치가 작동하지 않습니다.  (31).
Press any key to exit
```

```
nmrpflash.exe -i net22 -f RAX40-V1.0.5.104_1.0.1.img -R KO -vvv
```
i try this commnd 

os: window 11
device: rax40 v2

nmrpflash.exe -L result

```
net22  10.0.0.2         ***  ()
Press any key to exit
```

**Comment by jclehner** [comment]
Does this version work? Please post the full output when running with `-vv`.

[nmrpflash-0.9.17-5-g36900f2-win32.zip](https://github.com/jclehner/nmrpflash/files/9076526/nmrpflash-0.9.17-5-g36900f2-win32.zip)

**Comment by green1052** [comment]
not working

i/o wireless.. brabra

but use npcap instead wincap then working

**Comment by jclehner** [comment]
Thanks for the info, I've now added a warning message when using WinPcap instead of Npcap!
