### ISSUE TITLE
Trouble flashing router.

### ISSUE THREAD

**Issue by AngelFluffyOokami** [jclehner/nmrpflash#106]
Router: R7000
Hey there, I know this likely is a problem to do with firmware downgrade blocking, but I've bricked my router badly that I can't flash any image at all, and it constantly bootloops.
I tried looking around in the opened and closed issues for how the maintainer of this repo changes image version, even built my own freshtomato build from scratch with a higher version number to no avail.
I opened this issue thread to ask the maintainer how exactly I can modify the version number so I can do it myself were it to happen next time, as I cannot find much info at all online regarding it. I apoligize since this issue is not caused by nmrp itself.

Posted next is the info spit out by nmrp:
```.\nmrpflash.exe -i net5 -f .\freshtomato.chk
Advertising NMRP server on net5 ... -
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Uploading freshtomato.chk ... OK (7721018 b)
Waiting for remote to respond.
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 00:ff:ff:ff:ff:ff.
Sending configuration: 10.164.183.253/24.```

**Comment by banyip** [comment]
> Router: R7000 Hey there, I know this likely is a problem to do with firmware downgrade blocking, but I've bricked my router badly that I can't flash any image at all, and it constantly bootloops. I tried looking around in the opened and closed issues for how the maintainer of this repo changes image version, even built my own freshtomato build from scratch with a higher version number to no avail. I opened this issue thread to ask the maintainer how exactly I can modify the version number so I can do it myself were it to happen next time, as I cannot find much info at all online regarding it. I apoligize since this issue is not caused by nmrp itself.
> 
> Posted next is the info spit out by nmrp:
> 
> ```
> Advertising NMRP server on net5 ... -
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.
> Received upload request without filename.
> Uploading freshtomato.chk ... OK (7721018 b)
> Waiting for remote to respond.
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.
> Received CONF_REQ while waiting for TFTP_UL_REQ!
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.
> Received CONF_REQ while waiting for TFTP_UL_REQ!
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.
> Received CONF_REQ while waiting for TFTP_UL_REQ!
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.
> Received CONF_REQ while waiting for TFTP_UL_REQ!
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.
> Received CONF_REQ while waiting for TFTP_UL_REQ!
> Received configuration request from 00:ff:ff:ff:ff:ff.
> Sending configuration: 10.164.183.253/24.```
> ```

the same ploebelm. did found the solution?

**Comment by AngelFluffyOokami** [comment]
> the same ploebelm. did found the solution?

Not yet, aside from compiling my own tomatobuild, I have tried nothing no more. As much as I need the router, I just gave up on it for now.

**Comment by jclehner** [comment]
To change the version info, use my [patchchk](https://github.com/jclehner/patchchk) utility!
