### ISSUE TITLE
Readme ... waiting time before reboot for user to pay enough attention

### ISSUE THREAD

**Issue by RE3CON** [jclehner/nmrpflash#108]
Should in Readme inform that the process after flash file uploaded successfully, by counting receiving ping responce ...up to 11 will take some minutes at least more than 5 more likely 11 to 12 minutes. 
Where you have to be very patient "Waiting for remote to respond."
And until this appears....
"Received keep-alive request (11)". From 1 to 11 go at least 5-11 minutes.
No matter how I tried today to recover a Netgear R6260 with the Netgear methods as written here https://kb.netgear.com/000059633/How-do-I-upload-firmware-to-my-NETGEAR-router-using-a-TFTP-client-on-Microsoft-Windows
Or here https://kb.netgear.com/000059634/How-do-I-upload-firmware-to-my-NETGEAR-router-using-TFTP-from-the-Microsoft-Windows-Command-Prompt 
or even here https://kb.netgear.com/de/31504/Neuinstallation-der-Router-Firmware-ohne-das-Verwenden-des-CD-Recovery-Tools?language=de 
and on OpenWRT forums the instructions how to recover, no where is written that even after the firmware file have been successfully transfered into the router, you have to wait enough long until you can reboot. Otherwise the yellow LED will blinking again and report that the firmware is corrupt or missing as nothing have be done. Knowing this brings only the success.

**Comment by jclehner** [comment]
Thanks, I've added a [paragraph](https://github.com/jclehner/nmrpflash/blob/master/README.md#stuck-at-waiting-for-remote-to-respond) to the README file.
