### ISSUE TITLE
Flash R8000P OpenWRT image to R7900P

### ISSUE THREAD

**Issue by LokeYourLord** [jclehner/nmrpflash#109]
Hey there, curious how I would be able to use this to flash the R8000P OpenWRT newest stable release to the R7900P (because they had identical hardware and all). Look here for info: https://openwrt.org/toh/netgear/r8000p

I've tried to flash it, but I get back error messages as such:
![image](https://user-images.githubusercontent.com/5807595/190217192-b6733c76-850a-4e79-b006-8eea6fc31c94.png)

Now, I've really tried flashing it in any conceivable way I know about. I've tried flashing the recommended way, via the web interface, by renaming the file extension to .chk, but that didn't work, and then I've tried it via the [NETGEAR TFTP Method](https://kb.netgear.com/000059633/How-do-I-upload-firmware-to-my-NETGEAR-router-using-a-TFTP-client-on-Microsoft-Windows), and well... that also didn't work, the Router does not respond to the package at all and just boots up like it normally does.

Any advice on how I would flash the OpenWRT R8000P .bin file to the R7900P? Would appreciate it!

**Comment by LokeYourLord** [comment]
So, I've found a command that seems to work more or less, which is the following:
`nmrpflash.exe -v -i net13 -a 192.168.1.1 -A 192.168.1.10 -f openwrt-22.03.0-bcm4908-generic-netgear_r8000p-squashfs.bin`
However, even though it "uploads" the file and says "OK", it gets stuck at "Waiting for confirmation". After that, the Router boots but it boots into stock firmware. Power cycling it does nothing. Any idea?

**Comment by jclehner** [comment]
Thanks. This *should* have been fixed by 9eec3db, and will be included in the next release!
