### ISSUE TITLE
cannot use nmrpflash on my netgear r6220

### ISSUE THREAD

**Issue by ThomasKub** [jclehner/nmrpflash#11]
everytime i try to use the command:
nmrpflash.exe -i net2 -f R6220-V1.1.0.68_1.0.1.img
in my command prompt i get this return:
No response after 60 seconds. Bailing out.
ive already tried to add the macadress but it seems not to work anymore.

On this router is openwrt installed.
Hope you can help me.

**Comment by jclehner** [comment]
How did you connect the router to the device running nmrpflash?

**Comment by ThomasKub** [comment]
I use ethernet Port 1.

**Comment by jclehner** [comment]
And a cable goes from port 1 to the network interface "net2"? 

You need to run nmrpflash in the following manner:

* Turn off the R6220
* Start nmrpflash
* Turn on the R6220


What happens if you start nmrpflash

**Comment by wiewiur** [comment]
Hi, I have similar problem with R6220. I want to get back from openwrt to stock.
I've done following:
1) Connect laptop to R6220 via ethernet cable (to LAN1)
2) Turn off the R6220
3) Run:
sudo ./nmrpflash -i enx000ec6a477d0 -f fw.img -vv
on laptop (yes enx000ec6a477d0 is eth card)
4) Turn on the R6220

That give me:
```
Adding 10.164.183.253 to interface enx000ec6a477d0.
Advertising NMRP server on enx000ec6a477d0 ... \
Received configuration request from 9c:3d:cf:c5:b6:e8.
Sending configuration: 10.164.183.252, netmask 255.255.255.0.
rtnl_neigh_delete: Object not found
Received upload request without filename.
Using remote filename 'fw.img'.
Uploading fw.img ... sendto: Network is unreachable
```

**Comment by jclehner** [comment]
Please try with -a 192.168.1.1, and set 192.168.1.2 as the IP of your network interface. Does that work?

**Comment by wiewiur** [comment]
Worked!
I've done it but with 192.168.2.1 and 192.168.2.2 and got:

```
Received configuration request from 9c:3d:cf:c5:b6:e8.
Sending configuration: 192.168.2.1, netmask 255.255.255.0.
Using remote filename 'firmware'.
Uploading fw.img ... << WRQ(firmware, octet)
<< WRQ(firmware, octet)
>> ACK(0)
<< DATA(1)
>> ACK(1)
...
...
...
>> ACK(45491)
<< DATA(45492)
>> ACK(45492)
OK
Waiting for remote to respond.
Received keep-alive request.
...
a lot of ... "Received keep-alive request." (few minutes)
...
Received keep-alive request.
Remote finished. Closing connection.
Reboot your device now.

```
Thanks @jclehner !

I think its good to add this "Received keep-alive request." message to documentation, I was a little bit confused - should I restart router or not. I think I'm not alone.

**Comment by jclehner** [comment]
I've finally released 0.9.13, which fixes "Network unreachable" error described by @wiewiur. Closing this.

**Comment by limsko** [comment]
@Wiewiur you have saved my Day. I was rebooting router during Received keep-alive request instead of wait.
After reading your comment I gave my router more time to finiah job. Flashing was successfull.

**Comment by wretchey** [comment]
Guys can anyone please help. I’m unable to pass No response after 60 seconds. Bailing out. It is for my XR500 that has a constant red and white light active on power light

**Comment by NGOCodes** [comment]
Same issue here, mines bricked and I get the bailing out message

**Comment by jclehner** [comment]
You could try blind mode (`-B` option), but if that doesn't work, it could mean that the bootloader itself is corrupted. In that case, `nmrpflash` won't be able to unbrick your device, unfortunately.

Also, please don't hijack closed issues, but instead open a new one.
