### ISSUE TITLE
 IP address marked as deprecated

### ISSUE THREAD

**Issue by yousaf465** [jclehner/nmrpflash#112]
@jclehner facing this WNDR4300V2
```
C:\nmrp>nmrpflash -i net6 -f WNDR4300v2-V1.0.0.32.img
Waiting for Ethernet connection (Ctrl-C to skip).
Warning: IP address marked as deprecated.
Advertising NMRP server on net6 ... \pcap_sendpacket: send error: PacketSendPacket failed: The I/O operation failed because network media is disconnected or wireless access point is out of range.  (2150891551)
```
Using Ethernet, with Wifi turned off.
I have successfully restored the same router yesterday but when I tried to flash openwrt again it went into a boot loop after a manual restart. Now facing the above error since morning.  https://forum.openwrt.org/t/netgear-4300v2-bootlooping/138865/28?u=koa

**Comment by jclehner** [comment]
Please try this attached version. Does that fix your issue? 

[nmrpflash-0.9.18.2-1-g9eec3db-win32.zip](https://github.com/jclehner/nmrpflash/files/9735831/nmrpflash-0.9.18.2-1-g9eec3db-win32.zip)

**Comment by yousaf465** [comment]
https://youtu.be/U6koH1lSVCY this is happening right now

**Comment by jclehner** [comment]
Okay, that does help. On the router side, the line

```
Client starts...[Listening] for ADVERTISE...TTT
```

is the NMRP code listening for ADVERTISE packets. Each `T` represents a timeout that has elapsed without it having detected a packet. Only on the first boot, there's actually a delay between those. After that, `TTT` appears almost immediately.

Try this:

1. Turn off the router
2. Start nmrpflash, and press `Ctrl` + `C`
3. When it says "Advertising NMRP server on netX", turn on the router

**Comment by yousaf465** [comment]
> Okay, that does help. On the router side, the line
> 
> ```
> Client starts...[Listening] for ADVERTISE...TTT
> ```
> 
> is the NMRP code listening for ADVERTISE packets. Each `T` represents a timeout that has elapsed without it having detected a packet. Only on the first boot, there's actually a delay between those. After that, `TTT` appears almost immediately.
> 
> Try this:
> 
> 1. Turn off the router
> 2. Start nmrpflash, and press `Ctrl` + `C`
> 3. When it says "Advertising NMRP server on netX", turn on the router

The same, issue, TTT and it goes by and then reboots.
What Ip and DNS I should set in network adapter?

**Comment by jclehner** [comment]
Does this version change anything?

[nmrpflash-0.9.18.2-4-gb564180-win32.zip](https://github.com/jclehner/nmrpflash/files/9739665/nmrpflash-0.9.18.2-4-gb564180-win32.zip)

**Comment by yousaf465** [comment]
@jclehner Thanks this one worked with my own machine. Use USB to ethernet adapter and it lucky the first time.

**Comment by yousaf465** [comment]
https://forum.openwrt.org/t/netgear-4300v2-bootlooping/138865/33?u=koa 
Flashed back to OpenWrt using GUI, 
Will post a video on the process IA.

**Comment by jclehner** [comment]
It should be possible to flash an OpenWrt `-factory` image using `nmrpflash`. If that doesn't work, then it's possible that the version number [needs patching](https://github.com/jclehner/patchchk). 

Closing this, as the original issue has been resolved.
