### ISSUE TITLE
R8000P - NMRPflash TFTP Transfer Hang on Recieve Config

### ISSUE THREAD

**Issue by Xiseous** [jclehner/nmrpflash#116]
Thanks to @scrubmcnoob for the post, only good valid link I found about DD-WRT/OpenWRT/Tomato for R8000P.

I've followed this guide as well as a similar post (maybe by him as well) on the Netgear forum.

I've managed to get a successful upload, three times.

Twice with two different .bin files of OpenWRT (openwrt-21.02.1-bcm4908-generic-netgear_r8000p-squashfs & (openwrt-22.03.2-bcm4908-generic-netgear_r8000p-squashfs).

and once with the custom .chk file from here on the google drive.

**.BIN Files:** Using the .bin files it would sucessfully upload with no issues, and then say waiting for remote to respond, the router would do its thing and then I would be greated to the standard Netgear firmware (ouch), this happened with the newer versioned .bin as well.

**.CHK File:** Using the .CHK, it uploaded, received config, sent config and then got stuck there. It would leave the prompt on sending config, the router LED would have only the power on amber and the 1st port LED blinking in white (1000M link detected), I left it in this state for 10min, tried using the reset button, nothing happened (varied lengths up to 20sec) and then decided to turn the router off and back on, after this it started to continue normal behaviour and once restarted and pingable prompted me to the Netgear Genie :(.

NOTE: I did try the standard Tftpd64 that Netgear provides but that did absolutely nothing. Always stuck on #block 0 but I could have been doing something wrong there ([Link](https://kb.netgear.com/000059633/How-do-I-upload-firmware-to-my-NETGEAR-router-using-a-TFTP-client-on-Microsoft-Windows))

CHK File Link: https://drive.google.com/file/d/1mIFQEbHhoK4pU6C3Gh5-kW832yaBJWcJ/view
Similar Ticket Reference (by Scrubmcnoob): https://github.com/jclehner/nmrpflash/issues/89
Netgear Forum Post: https://community.netgear.com/t5/Nighthawk-WiFi-Routers/R8000P-V1-4-1-50-Update-workaround/m-p/2201116

### Reference
Hardware Version:        R8000P (X6S)
Firmware Version:         V1.4.4.94_1.3.56
GUI Language Version: V1.4.3.86_2.1.46.1
NMRPflash: Latest, Windows (with NpCap just in case)

**Comment by jclehner** [comment]
> Using the .CHK, it uploaded, received config, sent config and then got stuck there. It would leave the prompt on sending config

Please attach the output of `nmrpflash` in this case.
