### ISSUE TITLE
Not an issue, a question on RAX35 Version 1 block rollover

### ISSUE THREAD

**Issue by weaver666** [jclehner/nmrpflash#117]
Hi:

I have a bricked RAX35, version 1,. nmrpflash works fine to talk to it and upload the latest firmware, but it is too large and rolls over. Apparently the RAX35 can't deal with that. I haven't found a firmware smaller than 32 Mb. Are you aware of one?

Tried stock wait time, 1800 seconds and 3600 second wait time. Using MacBook Pro, Ventura macOS, connected to LAN port 1. The RAX35 WAN port is not connected.  Below is a typical result.

```
MacBook-Pro ~ % sudo nmrpflash -T 3600 -i en6 -f Downloads/RAX35-V1.0.5.104_1.0.1.img
Password:
Waiting for Ethernet connection (Ctrl-C to skip).
Advertising NMRP server on en6 ... -
Received configuration request from ...
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Uploading RAX35-V1.0.5.104_1.0.1.img ... Warning: TFTP block rollover. Upload might fail!
OK (39723217 b)
Waiting for remote to respond.
Timeout while waiting for 0000.
```

Thanks,

weaver666

**Comment by jclehner** [comment]
> [...] but it is too large and rolls over. Apparently the RAX35 can't deal with that. 

That may or may not be the issue. If the bootloader fails to handle that situation correctly, I'd expect it to either fail during the upload phase, or reject the image as corrupted (which usually results in the bootloader sending another upload request). Neither appears to happen here, so it's also possible that the flash chip is corrupted - not enough to brick the bootloader, but enough that flashing fails.

> I haven't found a firmware smaller than 32 Mb. Are you aware of one?

I'm not. However, I've tried slimming down the latest firmware somewhat (removing libraries intended for audio and video playback). Try flashing this firmware: https://drive.google.com/file/d/1bQZOZTybu2Q9g4i_U-dW_8RVLI_wjxs1/view?usp=share_link

**Comment by weaver666** [comment]
Thank you. I will try that file.

**Comment by weaver666** [comment]
I tried the file with no success:

MacBook-Pro ~ % sudo nmrpflash -i en6 -f Downloads/RAX35-V1.0.5.104_1.0.1_slim.uImage

Password:
Waiting for Ethernet connection (Ctrl-C to skip).
Advertising NMRP server on en6 ... |
Received configuration request from 10:0c:6b:ab:2e:44.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Uploading RAX35-V1.0.5.104_1.0.1_slim.uImage ... OK (31719564 b)
Waiting for remote to respond.
Timeout while waiting for 0000.

If the flash chip is corrupted, that's the end of the line for this router.

Thanks for your help.

**Comment by jclehner** [comment]
Do you live in Europe? If so, I might be interested in your bricked router, depending on how much shipping would cost.

**Comment by weaver666** [comment]
Joseph:

	No, I live in the United States.

	It occurs to me that this likely proves your program works with the RAX35 and macOS Ventura. So at least there is that.

Mark
