### ISSUE TITLE
R8000P flashing problems

### ISSUE THREAD

**Issue by lemonistas** [jclehner/nmrpflash#118]
Hi,

First of all thanks for the great tool. I tried flashing OpenWRT to my R8000P today but had issues transferring  the .bin file from https://openwrt.org/toh/netgear/r8000p as there is no .chk file provided to flash from the web GUI.  Thus, I tried nmrpflash to flash the .bin file but I encountered similar problems as mentioned in that issue: https://github.com/jclehner/nmrpflash/issues/116 .

My problem is that the .bin file gets copied over but afterwards it is stuck at "Waiting for remote to respond" and when I reboot the router I'm again greeted by the Netgear interface. 

I'm not familiar with the TFTP protocol and peculiarities but I think it might be connected with the timing of the put request in that particular router model as mentioned here https://community.netgear.com/t5/Nighthawk-WiFi-Routers/R8000P-V1-4-1-50-Update-workaround/m-p/2201116 . Still, I had no luck following that guide.

Any suggestions what to do?

Thanks a lot!

Update: Transferring original Netgear .chk firmware files via nmrpflash works, just the openwrt .img doesn't seem to work in my case.

**Comment by lemonistas** [comment]
Thank you so much for providing the .chk image. Strangely, I was able to flash that image via the Netgear web interface but after that the router wouldn't boot. So I hooked up a serial connection, interrupted the boot process and uploaded the OpenWRT .bin file via the CFE web interface which eventually let me boot OpenWRT on my R8000P. Do you know if there is any way to get WIFI working? 

Thanks again!

**Comment by jclehner** [comment]
> Do you know if there is any way to get WIFI working?

Not yet, since PCI support is not enabled in the current OpenWRT builds for this device.

**Comment by apollotsantos** [comment]
Adding to this, as I faced the same problems. What worked for me:

1.  Downgrade to the initial release version via the web UI (V1.4.4.94_1.3.56) (probably not needed)
2. Flash the image attached in [this comment](https://github.com/jclehner/nmrpflash/issues/118#issuecomment-1347148297) by @jclehner (thanks!) using `nmrpflash`, or this one for the latest version at the time of writing 

[openwrt-24.10.4-netgear_r8000p.chk.zip](https://github.com/user-attachments/files/24698985/openwrt-24.10.4-netgear_r8000p.chk.zip)

3. At this point, you should be able to access OpenWRT. If you try to upgrade openwrt via the sysupgrade image listed in the forum (note that it links to the same squashfs), it will bootloop.

**Comment by apollotsantos** [comment]
Update:  [25.12.0-rc2](https://downloads.openwrt.org/releases/25.12.0-rc2/) worked. Seems only 24 is broken. Here it goes 

[openwrt25rc2.zip](https://github.com/user-attachments/files/24699077/openwrt25rc2.zip)
