### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Mile-Lile** [jclehner/nmrpflash#12]
Hi jclehner ,
First of all, thx for your work. You helped many poople.
Could you make package for AUR pamac (arch linux)... it would help linux noobs like me...
I spent a lot of time to build from git and intall successful...
cheers,
mile-lile

**Comment by jclehner** [comment]
That's why I provide [pre-compiled binaries](https://github.com/jclehner/nmrpflash/releases). Have you tried those?
