### ISSUE TITLE
What commands are available with the -c option?

### ISSUE THREAD

**Issue by jeremiah-miller** [jclehner/nmrpflash#120]
Specifically I'm curious about the stock firmware, I'd like to change the DTIM interval to 3 on an R7000 but the config page doesn't have that option. But in general it seems like it might be useful to expand on that option a bit

**Comment by jclehner** [comment]
The command specified by `-c` runs on the computer running `nmrpflash`, *not* on the router!

What you're looking for is [telnet access to the router's Linux console](https://www.google.com/search?q=telnetenable+r7000).

**Comment by jeremiah-miller** [comment]
Oh cool, thank you!
