### ISSUE TITLE
Windows instructions not working?

### ISSUE THREAD

**Issue by NfNitLoop** [jclehner/nmrpflash#121]
Thanks for writing this tool!  I *think* I'm following the instructions correctly, but I'm seeing different behavior on my Windows 11 machine.

First I downloaded [nmrpflash 0.9.19][1].  

Then, I downloaded [npcap] v1.72.  Because I'm using nmrpflash 0.9.19, I did *not* check "WinPcap Compatibility" during installation.  Installation succeeded.

But when I run `nmrpflash -L` I still see:

> The code execution cannot proceed because wpcap.dll was not found. Reinstalling the program may fix this problem.

I tried reinstalling npcap and restarting the machine, but neither changed anything.

I also tried running nmrpflash from an command line that is running as administrator. There, I don't get the DLL error, but I get no output, even with `nmrpflash.exe -L -vvv`.

[1]: https://github.com/jclehner/nmrpflash/releases/tag/v0.9.19
[npcap]: https://npcap.com/#download

**Comment by NfNitLoop** [comment]
Aha.  I DID need to enable "WinPcap Compatibility" even though Im' using nmrpflash 0.9.19.  This part of the instructions is misleading!

> For nmrpflash versions prior to 0.9.14, install Npcap with "WinPcap Compatibility" enabled.

It seems you need to do that for 0.9.19 too.

**Comment by jclehner** [comment]
Yes, you're right.  I've updated the readme. Thanks!
