### ISSUE TITLE
No suitable interfaces found.

### ISSUE THREAD

**Issue by Maple38** [jclehner/nmrpflash#122]
Hey, I’m having an issue doing `nmrpflash -L`, it just tells me there are no suitable interfaces found. I have npcap installed with the winpcap comparability already. What should I do to fix this? Should I be connected to the partially-bricked router with a static IP or something?

**Comment by jclehner** [comment]
Please post the output of `nmrpflash -vvL`!

**Comment by ragebflame** [comment]
Hi,
Just adding to this issue thread as I am experiencing the same issue. Output of `nmrpflash.exe -vvL`:

```text
\Device\NPF_{EBB91ED1-D50B-442A-B10F-6A2D0E8A2EEB}  (not an ethernet device)
\Device\NPF_{A9750317-0064-428B-8A3B-658850EFA900}  (not an ethernet device)
\Device\NPF_{73C0C68A-4211-4D6B-BF82-278E2596C2AE}  (not an ethernet device)
\Device\NPF_{F7C712FA-4CC5-4905-A536-5D1A66A4694B}  (not an ethernet device)
\Device\NPF_{5BF4D649-AC90-4D47-84F1-A775A81CD83C}  (virtual interface)
\Device\NPF_{FAA40068-87B8-42EE-BCE3-C03386C846B3}  (virtual interface)
\Device\NPF_{DA69189D-89B5-4D28-82CB-E96864C4EDD7}  (virtual interface)
\Device\NPF_Loopback  (loopback device)
\Device\NPF_{A3B5C922-57C1-4646-AC43-3CAE55D12791}  (virtual interface)
No suitable network interfaces found.
```
Some of these are valid Ethernet devices. As reported by Wireshark:
![image](https://user-images.githubusercontent.com/1416300/233780842-629cad62-ca3b-4ebf-8b92-3f1d7bd37807.png)

**Comment by jclehner** [comment]
Which version of Windows is that? 10? 11?

**Comment by jclehner** [comment]
Please try this version, and if it still doesn't work, run it with `-vvvL` (one extra `v`), and post the output!

[nmrpflash-0.9.20-dev-win32.zip](https://github.com/jclehner/nmrpflash/files/11301414/nmrpflash-0.9.20-dev-win32.zip)

**Comment by ragebflame** [comment]
> Which version of Windows is that? 10? 11?

![image](https://user-images.githubusercontent.com/1416300/233787234-7adb45f0-1994-42ad-bc09-7efb8f6c7bbf.png)

**Comment by ragebflame** [comment]
> Please try this version, and if it still doesn't work, run it with `-vvvL` (one extra `v`), and post the output!
> 
> [nmrpflash-0.9.20-dev-win32.zip](https://github.com/jclehner/nmrpflash/files/11301414/nmrpflash-0.9.20-dev-win32.zip)

This version is working with a bare `-L` parameter:

```text
C:\...\nmprflash>nmrpflash.exe -L
net26  0.0.0.0          18:c0:4d:98:47:50  (Ethernet One)
```

**Comment by jclehner** [comment]
Fixed in the [latest release](https://github.com/jclehner/nmrpflash/releases).

**Comment by ragebflame** [comment]
> Fixed in the [latest release](https://github.com/jclehner/nmrpflash/releases).

Thanks a million @jclehner. This must be the quickest I've ever seen an issue fixed after raising it. Bravo.
