### ISSUE TITLE
Problems running on Windows 

### ISSUE THREAD

**Issue by Stavinair** [jclehner/nmrpflash#125]
![image](https://user-images.githubusercontent.com/57328437/230689758-c19cce83-83ce-4892-bcd4-15e8643bcc2c.png)
![image](https://user-images.githubusercontent.com/57328437/230689776-d125bd97-b077-4b4a-a366-6d5f9c62a2c2.png)

I opened it from command promp, also from powershell. It just autofills the prompt and then after I press a key it closes. What the hell is going on here? I have the factory image https://openwrt.org/toh/netgear/r6120 directed to me, INSIDE THE SAME FOLDER.

![image](https://user-images.githubusercontent.com/57328437/230690565-f03025bd-01e0-4020-ac87-f3cc1d77b419.png)
![image](https://user-images.githubusercontent.com/57328437/230694745-5c2f8bf1-5aa9-4934-b7e0-46ab751e839a.png)
I am admin on my laptop. And yes I tried running it in admin mode with powershell and the command prompt

**Comment by Stavinair** [comment]
I have barely any experience with command prompt but this doesn't seem normal

**Comment by Stavinair** [comment]
and yes I have 
![image](https://user-images.githubusercontent.com/57328437/230690809-e65ed4a9-7d05-49ac-8812-b12bcebdecd3.png)
installed, and I have scoured the net for answers but found none

**Comment by Stavinair** [comment]
I have tried it with the cable connected to the blue port when the router is off, and when it is on. I have then tried it on LAN port 1 when its both on and off

**Comment by Stavinair** [comment]
And yes I even ran it as admin.

**Comment by Stavinair** [comment]
Hello?

**Comment by jclehner** [comment]
I'm assuming you've already figured it out. For anyone else stubling across this issue, check out this howto:

https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt
