### ISSUE TITLE
Trying to flash expressvpn on to an R7000 router

### ISSUE THREAD

**Issue by andylink** [jclehner/nmrpflash#13]
I've played around with this for ages but haven't managed to crack it.

MBP connected directly via ethernet cable and ethernet to usb dongle

nmrpflash -i en7 -a 192.168.1.1 -A 192.168.1.10 -f express.chk -vvv

results in: -

Adding 192.168.1.10 to interface en7.
Advertising NMRP server on en7 ... |
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Using remote filename 'express.chk'.
Uploading express.chk ... << WRQ(express.chk, octet)
>> ACK(0)
<< DATA(1)
>> ACK(1)
.
.
.>> ACK(22272)
<< DATA(22273)
>> ACK(22273)
OK
Waiting for remote to respond.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received configuration request from 14:59:c0:89:f9:4c.
Sending configuration: 192.168.1.1, netmask 255.255.255.0.
192.168.1.1 (192.168.1.1) deleted
set: can only proxy for 192.168.1.1

Any pointers on what to do next?  I bought the R7000 especially for expressvpn router as they advised it was supported, obviously not since the latest firmware release.

Andy

**Comment by jclehner** [comment]
It looks like the image is rejected by the device, since it sends another upload request after the file has been transferred. Does flashing a stock image work?

**Comment by jclehner** [comment]
What happens if you use the latest firmware from https://kb.netgear.com/000060566/? Does `nmrpflash` work then?

**Comment by andylink** [comment]
Hi Joseph

It works fine. Can’t flash the router with anything other than Netgear firmware (tried expressvpn and. DD-WRT. 

Thanks for your help. 

Kind regards 

Andrew Calderbank-Link

**Comment by jclehner** [comment]
Hi @andylink  please see #14 for a modified dd-wrt image that *should* be flashable on your device!

**Comment by jclehner** [comment]
@andylink any news on this?

**Comment by andylink** [comment]
Hi

Sorry, no.  I'm working away at the moment so no access to the router, my
preference would be to flash it with expressvpnrouter so it's interesting
to know what is causing it to potentially fail (version number), I'll take
a look next week when I'm back home.

Many thanks

**Comment by jclehner** [comment]
No problem. If I'm right, you should be able to flash expressvpn from the
DD-WRT web interface! Keep me posted!

**Comment by andylink** [comment]
Hi

Good idea, hadn’t thought of that. Thank you. Will let you know how I get on. 

Kind regards 

Andrew Calderbank-Link

**Comment by jclehner** [comment]
Thanks for the feedback! Closing this, as it's not an issue in `nmrpflash` itself. I've opened a [PR](https://github.com/openwrt/openwrt/pull/1857) for OpenWRT, that should fix future issues of this kind.
