### ISSUE TITLE
Timeout waiting for Netgear Orbi flash to complete

### ISSUE THREAD

**Issue by SLKsander** [jclehner/nmrpflash#131]
Not a big deal but I am working with some newer Netgear Orbi gear and the flash after TFTP take longer.   I assumed the odd messages at the end of the upload were just a timeout problem but looking at Wireshark if appears the timeout is not be observed at all.   System is Rasp PI 400 running lastest version of Raspbian.  Keep-alives are coming without and delay/timeout.   Feels like  some timeout option not correctly set for this Linux version based on Debian.

Great utility and thanks for your work.

**Comment by SLKsander** [comment]
Wireshark for activity after TFPT completes attached.   No timeout for keep-alive packets.
[nmrpflash_750.pdf](https://github.com/jclehner/nmrpflash/files/12112589/nmrpflash_750.pdf)

**Comment by jclehner** [comment]
Please post the full output of your `nmrpflash` command, including `-vv`.

From what I gather, the keep-alive request is sent _by nmrpflash_ after the successful upload - this has been changed recently - are you sure you're using the latest version?

**Comment by SLKsander** [comment]
Yes, sure I am using latest version.  Will gather output and send shortly.

Thanks,

Scott

On Jul 20, 2023, at 3:22 PM, Joseph C. Lehner ***@***.***> wrote:

﻿
---- External Email: Use caution with attachments, links, or sharing data ----


Please post the full output of your nmrpflash command, including -vv.

From what I gather, the keep-alive request is sent by nmrpflash after the successful upload - this has been changed recently - are you sure you're using the latest version?

**Comment by SLKsander** [comment]
I confirmed I have source for v0.9.20 downloaded directly from GitHub.

Output follows.  I also posted the Wireshark output to the issues but included a link here to full capture.

https://www.dropbox.com/scl/fi/km722vkl3ikf2i0e88bez/nmrpflash_750.pcapng?rlkey=zo2fhkg1iv5c9747eldvvvull&dl=0

Notice that after the TFTP completes, the "Ignore ..." output in rapid succession without delays/timeout.   Also, same failure on multiple Netgear Orbi models.   On the 800 series, the flash after TFTP takes about 25 seconds.  Future models will be longer.

Let me know what else I can provide.

Thanks much,

Scott


***@***.***:~/Desktop/Firmware$ nmrpflash -vvv
Usage: nmrpflash [OPTIONS...]

Options (-i, and -f or -c are mandatory):
-a <ipaddr>     IP address to assign to target device [10.164.183.253]
-A <ipaddr>     IP address to assign to selected interface [10.164.183.252]
-B              Blind mode (don't wait for response packets)
-c <command>    Command to run before (or instead of) TFTP upload
-f <firmware>   Firmware file
-F <filename>   Remote filename to use during TFTP upload
-i <interface>  Network interface directly connected to device
-m <mac>        MAC address of target device (xx:xx:xx:xx:xx:xx)
-M <netmask>    Subnet mask to assign to target device [255.255.255.0]
-t <timeout>    Timeout (in milliseconds) for NMRP packets [10000 ms]
-T <timeout>    Time (seconds) to wait after successfull TFTP upload [1800 s]
-p <port>       Port to use for TFTP upload [69]
-R <region>     Set device region (NA, WW, GR, PR, RU, BZ, IN, KO, JP)
-S <n>          Skip <n> bytes of the firmware file
-v              Be verbose
-V              Print version and exit
-L              List network interfaces
-h              Show this screen

Example: (run as root)

# nmrpflash -i eth0 -f firmware.bin

When using -c, the environment variables IP, PORT, NETMASK
and MAC are set to the device IP address, TFTP port, subnet
mask and MAC address, respectively.

nmrpflash , Copyright (C) 2016-2022 Joseph C. Lehner
nmrpflash is free software, licensed under the GNU GPLv3.
Source code at https://github.com/jclehner/nmrpflash

libpcap version 1.10.0 (with TPACKET_V3)


Received configuration request from 6c:cd:d6:d3:9e:a3.
Sending configuration: 10.164.183.253/24.
Received upload request: filename 'firmware'.
Using remote filename 'firmware'.
Uploading RBR750-V7.2.6.19_5.0.18-signed.chk ... << WRQ(firmware, octet)
<< WRQ(firmware, octet)
>> ACK(0)
<< DATA(1)

<< DATA(43017)
>> ACK(43017)
<< DATA(43018)
>> ACK(43018)
OK (55579546 b)
Waiting for remote to respond.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Ignoring extra upload request.
Received configuration request from 6c:cd:d6:d3:9e:a3.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 6c:cd:d6:d3:9e:a3.
Sending configuration: 10.164.183.253/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 6c:cd:d6:d3:9e:a3.
Sending configuration: 10.164.183.253/24.
Timeout while waiting for TFTP_UL_REQ.

**Comment by jclehner** [comment]
Thanks for the Wireshark dumps! It looks like `nmrpflash` is confused by the "Configuration request" and "Upload request" packets which are sent by the device *after* the first TFTP packet has been sent (in your dump, packets after #144 and before #166).

Please try the latest commit, and post the output (running with `-vv` should suffice).

**Comment by SLKsander** [comment]
No joy.

Output and Wireshark attached.

Scott

Advertising NMRP server on eth0 ... -
Advertising NMRP server on eth0 ... \
Advertising NMRP server on eth0 ... |
Received configuration request from 6c:cd:d6:d3:9e:a3.
Sending configuration: 10.164.183.253/24.
Received upload request: filename 'firmware'.
Using remote filename 'firmware'.
Uploading RBR750-V4.6.7.13_2.1.9-signed.chk ... << WRQ(firmware, octet)
<< WRQ(firmware, octet)
>> ACK(0)
Drained 10 packet(s) from rx buffer
| << DATA(1)
<< DATA(1)
<< DATA(1)
<< DATA(1)
<< DATA(1)

**Comment by jclehner** [comment]
No wireshark dumps unfortunately!

**Comment by SLKsander** [comment]
Sorry.   Attached.

Scott

**Comment by SLKsander** [comment]
Anything more a can provide to help?

Scott

On Jul 26, 2023, at 5:53 AM, Joseph C. Lehner ***@***.***> wrote:

﻿
---- External Email: Use caution with attachments, links, or sharing data ----


Thanks for the Wireshark dumps! It looks like nmrpflash is confused by the "Configuration request" and "Upload request" packets which are sent by the device after the first TFTP packet has been sent (in your dump, packets after #144 and before #166).

Please try the latest commit, and post the output (running with -vv should suffice).

**Comment by jclehner** [comment]
Email attachments don't work on github. You'll have to upload it to dropbox, like the one before, or attach it directly from the [github issues page](https://github.com/jclehner/nmrpflash/issues/131).

**Comment by SLKsander** [comment]
Didn't realize that.   Sorry.   Wireshark capture on Dropbox

                https://www.dropbox.com/scl/fi/km722vkl3ikf2i0e88bez/nmrpflash_750.pcapng?rlkey=zo2fhkg1iv5c9747eldvvvull&dl=0

Scott

**Comment by jclehner** [comment]
Please try again with the latest commits!

**Comment by SLKsander** [comment]
Looks good.   Output below.   Will test with other models later today.

Do you want to see the Wireshark output?

Scott

Waiting for Ethernet connection (Ctrl-C to skip).
Adding 10.164.183.252 to interface eth0.
Advertising NMRP server on eth0 ... \

Advertising NMRP server on eth0 ... /
Received configuration request from 6c:cd:d6:d3:9e:a3.
Sending configuration: 10.164.183.253/24.
Received upload request: filename 'firmware'.
Using remote filename 'firmware'.
Uploading RBR750-V4.6.7.13_2.1.9-signed.chk ... Drained 1 packet(s) from rx buffer
| / - \ | / - \ | / - \

- \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | OK (67505766 b)
Waiting for remote to respond.
Remote finished. Closing connection.
Reboot your device now.

**Comment by jclehner** [comment]
Thanks, closing this now!
