### ISSUE TITLE
procedure entry point pcap_inject could not be loaded in DLL nmrpflash.exe

### ISSUE THREAD

**Issue by AlexcFrench** [jclehner/nmrpflash#134]
Hi,

I've got a strange issue whenever I run the .exe on Windows 11 (as administrator FYI). I'm using the prebuilt .exe from your github page

![image](https://github.com/jclehner/nmrpflash/assets/50441234/6df6e46d-2ce9-4310-bcf6-cebb95cfbdde)

The latest version of npcap is installed and I've uninstalled / reinstalled the LWF driver

-vvv also gives the same error...

Any help would be appreciated.
Thanks

**Comment by jclehner** [comment]
Not sure how this happened, but I've rebuild it and tested in on Windows and it should work now. The updated `.zip` can be found in the [releases section](https://github.com/jclehner/nmrpflash/releases/tag/v0.9.21).
