### ISSUE TITLE
procedure entry point pcap_set_immediate_mode could not be located...

### ISSUE THREAD

**Issue by AlexcFrench** [jclehner/nmrpflash#135]
Hi,

Using the latest version (14 mins old!) and it's fixed the first problem but now getting this error:
![image](https://github.com/jclehner/nmrpflash/assets/50441234/2df156f5-a58c-4624-8023-ec023e97a019)

-vvv gives the same error...

Are there any .dll's it's expecting in the path or similar ???

Win11, 22H2

Thanks

**Comment by jclehner** [comment]
That's weird. Please try the version below. Have you installed Npcap with "WinPcap compatibility" enabled?

[nmrpflash-0.9.21-win32.zip](https://github.com/jclehner/nmrpflash/files/12741287/nmrpflash-0.9.21-win32.zip)

**Comment by jclehner** [comment]
Also, are you using the [latest Npcap version](https://npcap.com/#download)?

**Comment by jclehner** [comment]
Any update on this?

**Comment by AlexcFrench** [comment]
Hiya,

Sorry - busy with work. So.. no, still not working on the original system I was using it on (with the latest npcap) and still failing. However, I have tried on a Win10 laptop and another Win11 machine and it's fine.

So I'm going to close this as a 'something funny with one of my machines' issue rather than a bug.

Sorry to have troubled you!

**Comment by Jack-Xiao** [comment]
I encountered the same issue and reloved with following steps:

1. Uninstall the old version of WinPcap (if installed):
2. Go to Control Panel > Programs and Features, locate WinPcap, and uninstall it.
3. Download the latest version of Npcap from the [Npcap official website](https://npcap.com/).
4. During installation, make sure to check the option “Install Npcap in WinPcap API-compatible mode”.
5. Restart your computer and run the program again.
