### ISSUE TITLE
R8000 - Timeout while waiting for ACK(1)

### ISSUE THREAD

**Issue by Gitfoe** [jclehner/nmrpflash#137]
When updating my Netgear R8000 from OpenWrt 22.03.5 to the latest snapshot of this morning, my router got bricked.

The router initially seems to be booting up fine (looking at the lights) and pressing the reset button makes the router reset/reboot. But after about 37 seconds with the router on, it reboots once (power light flashes white) and then nothing works anymore. It looks a little bit like this:
- 0 seconds: I press the router's power button, router powers up, LEDs start dancing
- 7 seconds later: power LED is solid orange, Ethernet 1 LED turns on, a couple TTL=100 pings were successful
- 30 seconds later: power LED turns white, starts blinking, and router reboots, after that the power LED stays solid white and Ethernet 1 LED is on, but router is inaccessible

I tried nmrpflash 0.9.21 to flash the stock firmware back to the router, but it does not work for me. I always end up with `Timeout while waiting for ACK(1)`. I tried both OpenWrt 22.03.5 and the newest v1.0.4.84 stock firmware, disabling my Windows firewall, using an Ubuntu VM with a bridged network interface, directly connecting to LAN port 1 on the router and with a switch in between, but I keep getting the same results. Moreover, looking at Windows task manager, I see some network activity when the connection is established, but after that nothing.

When nmrpflash is uploading to the router, pings to 192.168.1.1 continue working with TTL=100 for about 1 minute up until the ACK(1) timeout message is shown. About 30 seconds later, the power LED turns white, starts blinking, and the router reboots, just like what happens eventually when I just turn on the router and do nothing like described above.

I tried multiple commands, but this is one of the commands I ended up using. They all ended up with an ACK(1) timeout anyways.
`.\nmrpflash.exe -i net30 -f openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk -a 192.168.1.1 -m 2c:30:33:ab:cd:ef -F firmware -vvv`

The full log:
```{EFFC911E-9138-4143-9785-A9463B00A974}: Type=6, Name=Ethernet
Waiting for Ethernet connection (Ctrl-C to skip).
Advertising NMRP server on net30 ... /
Received configuration request from 2c:30:33:ab:cd:ef.
Sending configuration: 192.168.1.1/24.
Using remote filename 'firmware'.
Uploading R8000-V1.0.4.84_10.1.84.chk ... << WRQ(firmware, octet)
>> ACK(0)
Drained 10 packet(s) from rx buffer
<< DATA(1)
>> ACK(0)
>> ACK(0)
<< DATA(1)
<< DATA(1)
<< DATA(1)
<< DATA(1)
Timeout while waiting for ACK(1).
Press any key to exit

**Comment by jclehner** [comment]
Does using the [previous version](https://github.com/jclehner/nmrpflash/releases/tag/v0.9.20) fix your issue?

**Comment by pauliuspetk** [comment]
Hi, I am having the exact same issue. Running the latest version of Npcap (1.77); ticked the 'restrict Npcap driver usage to administrators' and 'install in WinPcap compatible mode' checkboxes when installing. Running nmrpflash as Administrator.

Tried both v0.9.21 and v0.9.20, no difference. Tried with pressing the reset button and without.
```
D:\r8000>nmrpflash.exe -i net22 -f openwrt-23.05.0-rc4-bcm53xx-generic-netgear_r8000-squashfs.chk -vvv
  {F6xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxAE}: Type=6, Name=Ethernet
Waiting for Ethernet connection (Ctrl-C to skip).
Adding 10.164.183.252 to interface net22.
Advertising NMRP server on net22 ... /
Received configuration request from a0:63:91:aa:bb:cc.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Using remote filename 'openwrt-23.05.0-rc4-bcm53xx-generic-netgear_r8000-squashfs.chk'.
Uploading openwrt-23.05.0-rc4-bcm53xx-generic-netgear_r8000-squashfs.chk ... << WRQ(openwrt-23.05.0-rc4-bcm53xx-generic-netgear_r8000-squashfs.chk, octet)
>> ACK(0)
Drained 10 packet(s) from rx buffer
<< DATA(1)
>> ACK(0)
>> ACK(0)
<< DATA(1)
<< DATA(1)
<< DATA(1)
<< DATA(1)
Timeout while waiting for ACK(1).

D:\r8000>nmrpflash.exe -i net22 -vvv -f R8000-V1.0.4.76_10.1.82.chk
  {F6xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxAE}: Type=6, Name=Ethernet
Waiting for Ethernet connection (Ctrl-C to skip).
Adding 10.164.183.252 to interface net22.
Advertising NMRP server on net22 ... |
Received configuration request from a0:63:91:aa:bb:cc.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Using remote filename 'R8000-V1.0.4.76_10.1.82.chk'.
Uploading R8000-V1.0.4.76_10.1.82.chk ... << WRQ(R8000-V1.0.4.76_10.1.82.chk, octet)
>> ACK(0)
Drained 10 packet(s) from rx buffer
<< DATA(1)
>> ACK(0)
>> ACK(0)
<< DATA(1)
<< DATA(1)
<< DATA(1)
<< DATA(1)
Timeout while waiting for ACK(1).
```

**Comment by pauliuspetk** [comment]
v0.9.20 is works fine after all, only v0.9.21 is failing.

Here are the serial logs from both versions:

**v0.9.20:** _(succeeded just fine, stays at the bootloader shell after flashing, need to power cycle to boot into the new firmware)_
```
CFE for Foxconn Router R8000 version: v1.0.8
Build Date: Fri May 30 15:03:06 CST 2014
Init Arena
Init Devs.
Boot up from NAND flash...
Bootcode Boot partition size = 524288(0x80000)
DDR Clock: 800 MHz
Info: DDR frequency set from clkfreq=1000,*800*
et2: Broadcom BCM47XX 10/100/1000 Mbps Ethernet Controller 7.14.43.2 (r474543)
CPU type 0x0: 1000MHz
Tot mem: 262144 KBytes

Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 192.168.1.1, mask 255.255.255.0
        gateway not set, nameserver not set
CONF-REQ sent...Waiting for CONF-ACK...
Recv DEV-REGION(0x0000) ST-UP(0x00000000)
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
TFTP-UL-REQ sent...Waiting for TFTP-WRQ...
Reading :: Done. 8912954 bytes read
Programming...done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 524346 bytes written
done. 8912954 bytes written
Skip writing CHK checksum for nflash.
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
CLOSE-REQ sent...Waiting for CLOSE-ACK...
CFE>
```

**v0.9.21**: _(throws a 'Timeout occured' quickly, around the same time the first '>> ACK(0)' is printed by app, and after failing to flash continues to boot existing image)_
```
CFE for Foxconn Router R8000 version: v1.0.8
Build Date: Fri May 30 15:03:06 CST 2014
Init Arena
Init Devs.
Boot up from NAND flash...
Bootcode Boot partition size = 524288(0x80000)
DDR Clock: 800 MHz
Info: DDR frequency set from clkfreq=1000,*800*
et2: Broadcom BCM47XX 10/100/1000 Mbps Ethernet Controller 7.14.43.2 (r474543)
CPU type 0x0: 1000MHz
Tot mem: 262144 KBytes

Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 192.168.1.1, mask 255.255.255.0
        gateway not set, nameserver not set
CONF-REQ sent...Waiting for CONF-ACK...
Recv DEV-REGION(0x0000) ST-UP(0x00000000)
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
TFTP-UL-REQ sent...Waiting for TFTP-WRQ...
Reading :: Failed.: Timeout occured
Upgrade firmware failed!
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
TFTP-UL-REQ sent...Waiting for TFTP-WRQ...
Reading :: Failed.: Timeout occured
Upgrade firmware failed!
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
TFTP-UL-REQ sent...Waiting for TFTP-WRQ...
Reading :: Failed.: Timeout occured
Upgrade firmware failed!
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
TFTP-UL-REQ sent...Waiting for TFTP-WRQ...
Reading :: Failed.: Timeout occured
Upgrade firmware failed!
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
TFTP-UL-REQ sent...Waiting for TFTP-WRQ...
Reading :: Failed.: Timeout occured
Upgrade firmware failed!
Device eth0:  hwaddr A0-63-91-DB-34-94, ipaddr 10.164.183.253, mask 255.255.255.0
        gateway not set, nameserver not set
CONF-REQ sent...Waiting for CONF-ACK...
CONF-REQ sent...Waiting for CONF-ACK...
CONF-REQ sent...Waiting for CONF-ACK...
CONF-REQ sent...Waiting for CONF-ACK...
CONF-REQ sent...Waiting for CONF-ACK...
CONF-REQ sent...Waiting for CONF-ACK...
Checking crc...Loader:raw Filesys:raw Dev:nflash0.os File: Options:(null)
Loading: .
```

**Comment by jclehner** [comment]
@Gitfoe @pauliuspetk Can you test this version, and verify that it fixes your issue?

[nmrpflash-0.9.21-2-g3320915-win32.zip](https://github.com/jclehner/nmrpflash/files/12883608/nmrpflash-0.9.21-2-g3320915-win32.zip)

**Comment by pauliuspetk** [comment]
I won't be able to touch that router for a while. Hopefully @Gitfoe can verify

**Comment by causlayer** [comment]
I have an R8000 router, but unfortunately I don’t have a windows system, I have a macbook.

**Comment by jclehner** [comment]
@causlayer try this:

[nmrpflash-0.9.21-2-gbe59ee5-macos.zip](https://github.com/jclehner/nmrpflash/files/13010637/nmrpflash-0.9.21-2-gbe59ee5-macos.zip)

**Comment by causlayer** [comment]
> @causlayer try this:
> 
> [nmrpflash-0.9.21-2-gbe59ee5-macos.zip](https://github.com/jclehner/nmrpflash/files/13010637/nmrpflash-0.9.21-2-gbe59ee5-macos.zip)

-> % nmrpflash -L
en0              192.168.1.106    78:4f:43:8d:b0:47
p2p0             0.0.0.0          0a:4f:43:8d:b0:47
awdl0            0.0.0.0          0a:57:51:0d:5d:e3
llw0             0.0.0.0          0a:57:51:0d:5d:e3
en5              0.0.0.0          ac:de:48:00:11:22
en10             192.168.1.205    88:d7:f6:db:bd:8e
bridge0          0.0.0.0          82:dc:88:41:44:00
en1              0.0.0.0          82:dc:88:41:44:00
en2              0.0.0.0          82:dc:88:41:44:04
en3              0.0.0.0          82:dc:88:41:44:01
en4              0.0.0.0          82:dc:88:41:44:05
slayer@slayer [21时09分15秒] [~]
-> % sudo /Users/slayer/Downloads/nmrpflash -i en10 -f /Users/slayer/Documents/Software/MacBook/openwrt/package/openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk
Password:
Waiting for Ethernet connection (Ctrl-C to skip).
Advertising NMRP server on en10 ... /
Received configuration request from 28:80:88:2a:59:21.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Uploading openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk ... | Timeout while waiting for ACK(1).

**Comment by jclehner** [comment]
Have you tried the [previous version](https://github.com/jclehner/nmrpflash/releases/tag/v0.9.20) yet?

**Comment by causlayer** [comment]
> Have you tried the [previous version](https://github.com/jclehner/nmrpflash/releases/tag/v0.9.20) yet?

The previous version was fine, I tried it before。

**Comment by jclehner** [comment]
Please post the output of 

```
sudo /Users/slayer/Downloads/nmrpflash -i en10 -f /Users/slayer/Documents/Software/MacBook/openwrt/package/openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk -vv
```

**Comment by causlayer** [comment]
> 
> ```
> sudo /Users/slayer/Downloads/nmrpflash -i en10 -f /Users/slayer/Documents/Software/MacBook/openwrt/package/openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk -vv
> ```

sudo /Users/slayer/Downloads/nmrpflash -i en10 -f /Users/slayer/Documents/Software/MacBook/openwrt/package/openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk -vv
Password:
Adding 10.164.183.252 to interface en10.
Advertising NMRP server on en10 ... |
Received configuration request from 28:80:88:2a:59:21.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Using remote filename 'openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk'.
Uploading openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk ... Drained 10 packet(s) from rx buffer
| Timeout while waiting for ACK(1).

**Comment by jclehner** [comment]
Please try this version, and run both `nmrpflash -L` and the previous command, and post the output of both:

[nmrpflash-0.9.21-6-g4a814f3-macos.zip](https://github.com/jclehner/nmrpflash/files/13030478/nmrpflash-0.9.21-6-g4a814f3-macos.zip)

**Comment by jclehner** [comment]
I think I've got it!

[nmrpflash-0.9.21-10-ga045438-macos.zip](https://github.com/jclehner/nmrpflash/files/13030700/nmrpflash-0.9.21-10-ga045438-macos.zip)

**Comment by causlayer** [comment]
> I think I've got it!
> 
> [nmrpflash-0.9.21-10-ga045438-macos.zip](https://github.com/jclehner/nmrpflash/files/13030700/nmrpflash-0.9.21-10-ga045438-macos.zip)

sudo /Users/slayer/Downloads/nmrpflash -i en10 -f /Users/slayer/Documents/Software/MacBook/openwrt/package/openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk -vv
Password:
Adding 10.164.183.252 to interface en10.
Advertising NMRP server on en10 ... -
Received configuration request from 28:80:88:2a:59:21.
Sending configuration: 10.164.183.253/24.
Received upload request without filename.
Using remote filename 'openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk'.
Uploading openwrt-bcm53xx-generic-netgear_r8000-squashfs.chk ... Drained 0 packet(s) from rx buffer in 201 ms
OK (30539834 b)
Waiting for remote to respond.
Received keep-alive request (29).
Remote finished. Closing connection.
Reboot your device now.
