### ISSUE TITLE
"Ethernet cable is unplugged"

### ISSUE THREAD

**Issue by hippypink** [jclehner/nmrpflash#139]
Running Windows 10. 
If I had a linux computer, I would use it.

Running latest version of your software

Got network adaptar name using -L

nmrpflash.exe -i net18 -f 1.img

Netgear R7450
Still loads DD-WRT firmware I had put on it previously.

**Comment by jclehner** [comment]
Post the full output of both `nmrpflash.exe -L` and `nmrpflash.exe -i net18 -f 1.img -vv`. A screenshot is also acceptable.

**Comment by hippypink** [comment]
After rebooting, it worked. Wierd

**Comment by jclehner** [comment]
Thanks!
