### ISSUE TITLE
Orbi RBK753, i just want to change region code,

### ISSUE THREAD

**Issue by ttonyyao** [jclehner/nmrpflash#142]
nmrpflash - i net0 -R WW

When i do like this, it is showing the exmaple of how to use nmrpflash with a list of options and description? I am not sure if -f with firmware is a must agrument, and the region only can be changed during the firmwaring progress? hope to get your feedback

**Comment by ttonyyao** [comment]
@jclehner Hi Sir, look forward to hearing back from you

**Comment by jclehner** [comment]
Yes, at the moment, the `-R` command only works during a firmware upgrade. What's your current firmware version?

**Comment by ttonyyao** [comment]
> Yes, at the moment, the `-R` command only works during a firmware upgrade. What's your current firmware version?

Sir, my FW of RBR750 is 7.2.26.1 the latest version can be found on nethear. Is that workable of this version?

**Comment by jclehner** [comment]
Yes. In that case, try running 

```
nmrpflash.exe -i net0 -R WW -f RBR750-V7.2.6.21_5.0.20.chk
```

replacing `net0` with your network interface (as shown by `nmrpflash.exe -L`). 

Note that changing the region does not work on all routers, so it may or may not work.

**Comment by ttonyyao** [comment]
Thank you so much! I will give a try..

Thanks,Tony
