### ISSUE TITLE
R8000 - Stuck on Ack(0)

### ISSUE THREAD

**Issue by pato-pan** [jclehner/nmrpflash#143]
This program never seems to work with this router and it never seems to send any data. This may be related to #137 except it's Ack(0) with no data being sent, and I am not sure what Ack(0) is.

My router is currently using OpenWRT version 5.10.161 which I reset to default, I want to rollback to stock and I had no success so far

The steps I took are:
1. Router is off
2. I run the command `sudo nmrpflash -vvv -i enp4s0 -f R8000-V1.0.4.84_10.1.84.chk`
3. I turn on the router right after

Usually the router ends with power light white and ethernet 1 light orange, regardless of whether I do this or not.

I had tried pressing reset and keeping it pressed before turning on the router and also pressing reset as soon as the lights turn on. I also tried using every ethernet port.

```
sudo nmrpflash -vvv -a 192.168.1.1 -A 192.168.1.108 -i enp4s0 -f R8000-V1.0.4.84_10.1.84.chk
Temporarily disabling NetworkManager on interface.
Waiting for Ethernet connection (Ctrl-C to skip).
Advertising NMRP server on enp4s0 ... /
Received configuration request from 3c:37:86:cc:e3:07.
Sending configuration: 192.168.1.1/24.
Received upload request without filename.
Using remote filename 'R8000-V1.0.4.84_10.1.84.chk'.
Uploading R8000-V1.0.4.84_10.1.84.chk ... << WRQ(firmware, octet)
>> ACK(0)

```

CTRL+C doesn't work. If I run the command again after terminanting the application it gives me the error `rtnl_addr_add: Unspecific Failure" and I am always forced to restart my computer to run it again. I tried this on two computers so far.

**Comment by pato-pan** [comment]
Something I notice is that the configuration is being sent to 10.164.183.253/24 instead of 192.168.1.1/24 like in the example shown in the issue. I have the same gateway, 192.168.1.1, so it should be the same.

**Comment by jclehner** [comment]
1. Are you using the latest version of `nmrpflash`?  What's the output of `nmrpflash -v`?
2. Does the version attached below fix your issue?

[nmrpflash-0.9.22-12-gd810575-linux-x86_64.zip](https://github.com/jclehner/nmrpflash/files/14301596/nmrpflash-0.9.22-12-gd810575-linux-x86_64.zip)

**Comment by ParzivalWolfram** [comment]
Same issue on an R6080, this build worked when the AUR version did not. The `nmrpflash-bin` AUR package is an entirely corrupt AppImage and can't be run at all.

**Comment by Scotti007** [comment]
> 1. Are you using the latest version of `nmrpflash`?  What's the output of `nmrpflash -v`?
> 
>     2. Does the version attached below fix your issue?
> 
> 
> [nmrpflash-0.9.22-12-gd810575-linux-x86_64.zip](https://github.com/jclehner/nmrpflash/files/14301596/nmrpflash-0.9.22-12-gd810575-linux-x86_64.zip)

This Version fixed it for me too.
Had the same Problem, but with a R6020 and the R6020_V1.0.0.54.img while using 0.9.22 from Homebrew.
