### ISSUE TITLE
Invalid Interface

### ISSUE THREAD

**Issue by Schnowzer** [jclehner/nmrpflash#144]
First I am not very savvy on network coding but trying to Unbrick an R8000

I downloaded and ran NPCAP as advised. Then got the nmrpflash and the firmwear as suggested. I found the ethernet eth2. I put nmrpflash and the .chk file on my root C: drive

Shell didn't recognise the # but advised the required syntax
Then ran the following command:
.\nmrpflash -i eth2 -f R8000-V1.0.4.18_10.1.49.chk

C:\nmrrpflash.exe ran but said:
Invalid interface name.
Press any key to exit

I have reached the limit of my tapping ability. Any suggestions would be gratefully received. D

**Comment by jclehner** [comment]
Network Interfaces on Windows are named `netX`, not `ethX`, so I'm assuming you should have used `net2` instead (or whatever name is displayed by the `nmrpflash -L` command).

**Comment by Schnowzer** [comment]
Brilliant, Thanks JC that worked great. DM
