### ISSUE TITLE
Stuck in “Received keep-alive request” state

### ISSUE THREAD

**Issue by david-zzj** [jclehner/nmrpflash#145]
![image](https://github.com/jclehner/nmrpflash/assets/22125266/1a03aa48-eb06-462b-9053-a05ce762942b)

My router is R6800, i nmrpflashed padavan succeed, but it can't boot.
So i flashed back to stock, failed. Flashed to pandorabox, failed too. Nmrpflash stucked in “Received keep-alive request” state.
What can i do now? Please take me a way, thanks.

**Comment by david-zzj** [comment]
add -vv option

![image](https://github.com/jclehner/nmrpflash/assets/22125266/76c8d5da-a0c9-45ca-b5ed-0bb4da2fbd22)

**Comment by jclehner** [comment]
Is it actually stuck, or does the number keep counting up?

**Comment by david-zzj** [comment]
The number keep counting up.

**Comment by david-zzj** [comment]
Finally, I found the reason, the router's UBOOT was broken.
