### ISSUE TITLE
Unable to flash D7000 - Protocol Error

### ISSUE THREAD

**Issue by itsrajivshah** [jclehner/nmrpflash#15]
I've been having an issue flashing a D7000 router I just picked up.

My Macbook Pro is connected directly to the via an ethernet cable and ethernet to usb dongle

`nmrpflash -i en7 -f D7000-V1.0.1.70_1.0.1.img -vvv`

results in:
```
Adding 10.164.183.253 to interface en7.
Advertising NMRP server on en7 ... |
Received configuration request from [mac].
Sending configuration: 10.164.183.252, netmask 255.255.255.0.
delete: cannot locate 10.164.183.252
Received upload request without filename.
Using remote filename 'D7000-V1.0.1.70_1.0.1.img'.
Uploading D7000-V1.0.1.70_1.0.1.img ... << WRQ(D7000-V1.0.1.70_1.0.1.img, octet)
<< WRQ(D7000-V1.0.1.70_1.0.1.img, octet)
>> ACK(0)
<< DATA(1)
>> ACK(1)
<< DATA(2)
>> ACK(2)

ACK(0)
<< DATA(1)
ACK(1)
.
.
<< DATA(65532)
>> ACK(65532)
<< DATA(65533)
>> ACK(65533)
<< DATA(65534)
>> ACK(65534)
<< DATA(65535)
>> ACK(65535)
<< DATA(0)
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
Protocol error; bailing out.
```

As far as I'm aware, the D7000 is the same chipset as the R7000 but with a DSL modem attached, so I'm unsure as to why it's having issues.

Any ideas on what to do next? I have a UART into the router available for troubleshooting.

**Comment by jclehner** [comment]
Hi, please try [this version](https://github.com/jclehner/nmrpflash/files/3122616/nmrpflash-0.9.13-2-g2d4a594-osx.zip)!

**Comment by negan07** [comment]
tftp running on 192.168.1.1 cfe bootloader before kernel loading only

tftp upload can be used only on bootloader level bricked router (missing, empty or broken rootfs)

**Comment by itsrajivshah** [comment]
Thanks @jclehner have just given that binary a try. Same issue I'm afraid.

One thing that's interesting is that @negan07's Ancistrus monolithic firmware image can be loaded on fine with this method, it's just the stock Netgear ones that have been failing. I've gone back through the versions on Netgear's website and have found that this issue starts with the V1.0.1.x images (the V1.0.0.x images load fine)

**Comment by jclehner** [comment]
Please post the logs from the second try as well, especially the lines after `DATA(65535)`

The issue is likely caused by the fact that the firmware file exceeds 32 MiB, which causes a rollover of the TFTP block counter. Can you confirm that the newer images exceed this limit, while the older ones (those that worked) don't?

**Comment by itsrajivshah** [comment]
Sure thing, the lines are:

```>> ACK(65531)
<< DATA(65532)
>> ACK(65532)
<< DATA(65533)
>> ACK(65533)
<< DATA(65534)
>> ACK(65534)
<< DATA(65535)
>> ACK(65535)
<< DATA(1)
<< DATA(1)
<< DATA(1)
>> ACK(65535)
Expected ACK(1), got ACK(65535).
<< DATA(1)
<< DATA(1)
>> ACK(65535)
Expected ACK(1), got ACK(65535).
<< DATA(1)
<< DATA(1)
>> ACK(65535)
Expected ACK(1), got ACK(65535).
<< DATA(1)
<< DATA(1)
>> ACK(65535)
Expected ACK(1), got ACK(65535).
<< DATA(1)
<< DATA(1)
>> ACK(65535)
Expected ACK(1), got ACK(65535).
<< DATA(1)
<< DATA(1)
>> ACK(65535)
Expected ACK(1), got ACK(65535).
Protocol error; bailing out.
10.164.183.252 (10.164.183.252) deleted```

I've had a look at the firmware images and that seems to be the case - the images that work are all below 32MiB.

**Comment by jclehner** [comment]
Please try [this version](https://github.com/jclehner/nmrpflash/files/3126616/nmrpflash-0.9.13-4-g49b1568-osx.zip), which keeps the block counter at `65535` - this is non-standard behaviour, but *might* work, depending on the implementation!

**Comment by itsrajivshah** [comment]
Interesting - that seems to have fixed it! Thanks!

**Comment by jclehner** [comment]
The latest `.zip`, or the the command using the external `tftp` command?

**Comment by jclehner** [comment]
Please test this latest version, which only enables the hack if neccessary, and post the output too. That would be a great help for other users, as I can't test it myself.

[nmrpflash-0.9.13-5-gb3ba1c0-osx.zip](https://github.com/jclehner/nmrpflash/files/3137617/nmrpflash-0.9.13-5-gb3ba1c0-osx.zip)

**Comment by itsrajivshah** [comment]
Apologies it took me so long - I was away from this router for a while. Here's the command output from the newest version:

`>> ACK(65521)
<< DATA(65522)
>> ACK(65522)
<< DATA(65523)
>> ACK(65523)
<< DATA(65524)
>> ACK(65524)
<< DATA(65525)
>> ACK(65525)
<< DATA(65526)
>> ACK(65526)
<< DATA(65527)
>> ACK(65527)
<< DATA(65528)
>> ACK(65528)
<< DATA(65529)
>> ACK(65529)
<< DATA(65530)
>> ACK(65530)
<< DATA(65531)
>> ACK(65531)
<< DATA(65532)
>> ACK(65532)
<< DATA(65533)
>> ACK(65533)
<< DATA(65534)
>> ACK(65534)
<< DATA(65535)
>> ACK(65535)
<< DATA(0)
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
Transmitting rest of file as block 65535.
<< DATA(0)
<< DATA(0)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
Timeout while waiting for ACK(65535).
10.164.183.252 (10.164.183.252) deleted`

**Comment by jclehner** [comment]
Hmm... Can you retry with [this binary](https://github.com/jclehner/nmrpflash/files/3458267/nmrpflash-0.9.13-9-g1724f8b-osx.zip)?

**Comment by itsrajivshah** [comment]
This is the output I'm getting with the new binary:

`<< DATA(65514)
>> ACK(65514)
<< DATA(65515)
>> ACK(65515)
<< DATA(65516)
>> ACK(65516)
<< DATA(65517)
>> ACK(65517)
<< DATA(65518)
>> ACK(65518)
<< DATA(65519)
>> ACK(65519)
<< DATA(65520)
>> ACK(65520)
<< DATA(65521)
>> ACK(65521)
<< DATA(65522)
>> ACK(65522)
<< DATA(65523)
>> ACK(65523)
<< DATA(65524)
>> ACK(65524)
<< DATA(65525)
>> ACK(65525)
<< DATA(65526)
>> ACK(65526)
<< DATA(65527)
>> ACK(65527)
<< DATA(65528)
>> ACK(65528)
<< DATA(65529)
>> ACK(65529)
<< DATA(65530)
>> ACK(65530)
<< DATA(65531)
>> ACK(65531)
<< DATA(65532)
>> ACK(65532)
<< DATA(65533)
>> ACK(65533)
<< DATA(65534)
>> ACK(65534)
<< DATA(65535)
>> ACK(65535)
<< DATA(0)
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
<< DATA(0)
<< DATA(0)
>> ACK(65535)
Expected ACK(0), got ACK(65535).
Transmitting rest of file as block 65535.
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
>> ACK(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
<< DATA(65535)
Timeout while waiting for ACK(65535).
10.164.183.252 (10.164.183.252) deleted`

**Comment by jclehner** [comment]
In May, you stated that you had successfully flashed the file. However, you didn't state whether you achieved this using the version of `nmrpflash` I had posted back then, or the command 
```
nmrpflash -i en7 -c 'echo -e "trace\nbinary\nput D7000-V1.0.1.70_1.0.1.img" | tftp $IP'
```

Which of these two did actually fix your issue?

**Comment by itsrajivshah** [comment]
I'm not 100% sure - I couldn't reproduce the success as mentioned later - the only thing I can think of is the Ancistrus file was being flashed instead of the Netgear one.

**Comment by jclehner** [comment]
I've reverse engineered the bootloader code, and unfortunately it looks like it's not possible to flash images greater than 32 MiB. The block counter is stored as a `uint32_t` which happily increments beyond `65535`, and once that happens, the comparison against the packet's `uint16_t` block number always fails.

In the next release, I'll make `nmrpflash` print a warning if the file size is beyond the TFTP limit.

**Comment by itsrajivshah** [comment]
Ah interesting, thanks for the heads up - I'll take this up with Netgear when I have a chance. Will close this issue as I don't think much else can be done
