### ISSUE TITLE
Successful nmrpflash on Netgear WNR3500U/L

### ISSUE THREAD

**Issue by xweebie** [jclehner/nmrpflash#16]
Connected router at 192.168.1.1 directly to computer ethernet.  I put nmrpflash.exe in system32 (Win10) and my firmware file on the root (C:).  Ran nmrpflash: nmrpflash -i net7 -f x.chk.  I powered router but it failed an ack.  Used the cursor key to quickly re-run nmrpflash and after a few tries of some type of timing difficulties between running the flash and router boot, it responded:
```
C:\>nmrpflash -i net7 -f x.chk
Advertising NMRP server on net7 ... \
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Uploading x.chk ... OK
Waiting for remote to respond.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Remote finished. Closing connection.
Reboot your device now.
```

Success! Thanks!

**Comment by jclehner** [comment]
Thanks for the feedback!
