### ISSUE TITLE
Feature request,

### ISSUE THREAD

**Issue by FrostKnight** [jclehner/nmrpflash#161]
Could you make an option for resetting password via nmrpflash?

I am not sure how to do this. And very often that fails to work.

Reflashing firmwarE? yes it works, resetting password? Not always...

**Comment by jclehner** [comment]
There's no mechanism in the NMRP protocol to do what you're asking. On some devices, flashing a firmware file also causes a factory reset, while on others it doesn't. There's nothing `nmrpflash` can do about it, unfortunately.
