### ISSUE TITLE
After flashing stock firmware i still get the LuCI Interface from OpenWrt

### ISSUE THREAD

**Issue by Aaron2550** [jclehner/nmrpflash#17]
Hey, I just flashed the stock firmware for my R6220 from netgear but when i try to connect to the router via 192.168.1.1 i get the LuCI Interface instead of the netgear one. See [this pic](https://files.catbox.moe/j2xz4e.png). routerlogin.net doesnt worke ither, it just brings me to https://www.netgear.com/home/products/networking/routerlogincom.html even after clearing my browser cache.

EDIT: my log is: [https://pastebin.com/fZAstkPb](https://pastebin.com/fZAstkPb)

**Comment by jclehner** [comment]
There's nohing in the logs indicating that flashing failed. Also, the screenshot you sent indicates that the original LuCI interface is no longer available error 404). What exactly happens if you navigate to [http://192.168.0.1](http://192.168.0.1)?

**Comment by Aaron2550** [comment]
Actually, i think i just now fixed it by flashing the stock image the 6th time... When i go to 192.168.0.1 nothing happens, connection just times out.

**Comment by Aaron2550** [comment]
> Also, the screenshot you sent indicates that the original LuCI interface is no longer available error 404).

Yes but when i went to 102.168.1.1 i was redirected to /cgi-bin/luci

**Comment by jclehner** [comment]
Strange. Theoretically, it's possible that flashing was still in progress when `nmrpflash` told you to reboot. ..
