### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Hobo2k** [jclehner/nmrpflash#18]
Hi,

When I try to compile with make I get this error:

make: pkg-config: Command not found
cc -c -Wall -g -DNMRPFLASH_VERSION=\"0.9.13-10-ged27079\"  ethsock.c -o ethsock.o
ethsock.c:42:10: fatal error: netlink/route/addr.h: No such file or directory
 #include <netlink/route/addr.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:24: ethsock.o] Error 1

How to fix this?

It's a Debian 10 x64 system.

Thanks.

**Comment by jclehner** [comment]
Make sure you install `build-essential` and `libnl-route-3-dev`.

**Comment by Hobo2k** [comment]
yes they are, but don't work

**Comment by jclehner** [comment]
Install `pkg-config`!
