### ISSUE TITLE
press any key to exit

### ISSUE THREAD

**Issue by jokson** [jclehner/nmrpflash#19]
run nmpflash.exe    popped up press any key to exit.
WIN7  64

**Comment by jclehner** [comment]
`nmrpflash` does not have a graphical user interface, so it needs to be run from the command prompt. See (this)[https://www.wikihow.com/Run-Exe-from-Cmd-on-PC-or-Mac] for information on how to do this.

**Comment by Cheguetomate** [comment]
Hi, the same thing happens to me but the link doesn't work.
