### ISSUE TITLE
not working on windows 10

### ISSUE THREAD

**Issue by amidevous** [jclehner/nmrpflash#20]
hello i flash my router netgear R6220

under openwrt more than a year ago today I wish I could reinstall the original firmware

but it does not work

version currently install openwrt 18.6.4

C:\Users\andy\Downloads\Compressed\R6220-V1.1.0.86>nmrpflash.exe -i net0 -f R6220-V1.1.0.86.img
Advertising NMRP server on net0 ... |
No response after 60 seconds. Bailing out.

please solve problem or create firmware en on.bin file

**Comment by amidevous** [comment]
following the information provide here

https://github.com/jclehner/nmrpflash/issues/11

I tried all the following command and it still does not work

nmrpflash.exe -a 192.168.1.1 -i net0 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.1.1 -i net1 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.1.1 -i net2 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.2.1 -i net0 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.2.1 -i net1 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.2.1 -i net2 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.3.1 -i net0 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.3.1 -i net1 -f R6220-V1.1.0.86.img -vv

nmrpflash.exe -a 192.168.3.1 -i net2 -f R6220-V1.1.0.86.img -vv

priory in this inssue the following command

sudo ./nmrpflash -i enx000ec6a477d0 -f fw.img -vv

but this command and for linux

I am under windows 10

and I do not have the possibility to put a linux

**Comment by amidevous** [comment]
I managed to turn on the router

start the program then turn it off and on again

but it's completely blocking it's more than an hour

who is on the firmware update page and who is telling me please be patient what should I do?

the loading bar and finish for a long time

and nothing is not working on the internet on the pc

and every time I try to refresh the page

it recomposes the configuration at the beginning

it's like he does not record any of the information I give him

**Comment by jclehner** [comment]
1. Were you finally able to flash with `nmrpflash`?
2. Did you wait for it to display `Remote finished. Closing connection.`?
3. In any case, run `nmrpflash` with `-vv` and post the output!
4. Don't just try `net1`, `net2`, etc. Use `nmrpflash -L` (without any other options) to print all network devices.

**Comment by ptrrssll** [comment]
I had a lot of trouble with the short 5 second Window on an r6400v2 to get the session open. In the end I found that holding in the reset, starting nmrpflash, then powering on and releasing the reset seemed the most reliable. You Must wait for an orderly session close or the flash has not completed properly. Remember to upload the img or chk file inside the zip and not the zip itself.

**Comment by PaoloGi** [comment]
same issue there 
if i start nmrpflash and the router is on:

```
c:\> nmrpflash -i net4 -f R6220.img -vv
net4: \Device\NPF_{4824445A-85E9-4EB1-AA2C-DF1966AD8765}
Adding 10.164.183.253 to interface net4.
Advertising NMRP server on net4 ... \
No response after 60 seconds. Bailing out.
```

If i switch off the router then start nmrpflash :

```
c:\> nmrpflash -i net4 -f R6220.img -vv
net4: \Device\NPF_{4824445A-85E9-4EB1-AA2C-DF1966AD8765}
Adding 10.164.183.253 to interface net4.
Failed to bind after 5 seconds: bind: The requested address is not valid in its context
```

**Comment by jclehner** [comment]
I'll investigate. In the meantime, try this:

1. Turn on the router.
2. Start nmrpflash.
3. Power cycle the router.
