### ISSUE TITLE
Works with Netgear R6400v2

### ISSUE THREAD

**Issue by ptrrssll** [jclehner/nmrpflash#21]
On an R6400v2 remove the CHK file from the zip you download from Netgear.
eg.  use -f R6400v2-V1.0.4.78_10.0.55.chk NOT ZIP

Note: I was bricked by an update to R6400v2-V1.0.4.82_10.0.57
I used nmrpflash to bring it back.

**Comment by gt7599a** [comment]
I was also able to use it on an r8000.

**Comment by maranov** [comment]
Dtto with R6400v2 and `R6400v2-V1.0.4.82_10.0.57.chk`.

Thanks @jclehner.

**Comment by jclehner** [comment]
Thanks for the feedback!
