### ISSUE TITLE
Netgear R7000P.   Waiting for CLOSE-ACK

### ISSUE THREAD

**Issue by alberttwong** [jclehner/nmrpflash#22]
My major issue is that board_id shows incorrectly with U12H270T00_NETGEAR due to me flashing tomato with the wrong firmware (R7000 not R7000P).  This resulted in bricked R7000P.   I was hoping that nmrpflash would correctly set the board_id to show U12H270T20_NETGEAR and unbrick my router. 

History context:
Netgear R7000P firmware -> WWDRT R7000P firmware -> Tomato R7000 (bricked system, tried to use other R7000P images but serial console to router showed that router rejected different firmware because the board_id now shows R7000 U12H270T00_NETGEAR, "nvram set board_id=U12H270T20_NETGEAR" did not persist across reboots) -> nmrpflash with "factory-to-dd-wrt.chk" (successfully did set to R7000P U12H270T20_NETGEAR and flashed to WWDRT R7000P firmware) 

-----

Here's the message on the router side. 

```
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 1048576 bytes written
KEEP-ALIVE-REQ sent...Waiting for KEEP-ALIVE-ACK...
done. 32826 bytes written
done. 29392954 bytes written
Skip writing CHK checksum for nflash.
Device eth0:  hwaddr 9C-3D-CF-50-34-51, ipaddr 10.164.183.252, mask 255.255.255.0
        gateway not set, nameserver not set
CLOSE-REQ sent...Waiting for CLOSE-ACK...
```

Client side.
```
MacBook-Pro-2 Downloads % sudo ./nmrpflash -i en7 -f factory-to-dd-wrt.chk
Advertising NMRP server on en7 ... -
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Uploading factory-to-dd-wrt.chk ... OK
Waiting for remote to respond.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
Remote finished. Closing connection.
Reboot your device now.
```

**Comment by alberttwong** [comment]
Update..... I just waited and waited.   No changes on the router side.   However when I rebooted, DDWRT came up.   Hurray!    I guess the ASK is to somehow know when to reboot the router???

**Comment by alberttwong** [comment]
@jclehner Are you part of  https://help.github.com/en/articles/about-github-sponsors.  I'd like to send money your way for this utility.

**Comment by jclehner** [comment]
Theoretically, `nmrpflash` should send a CLOSE_ACK before printing `Remote finished. Closing connection.` If you want this fixed, a `tcpdump` of the whole session would help.

> @jclehner Are you part of https://help.github.com/en/articles/about-github-sponsors. I'd like to send money your way for this utility.

If you insist, the email address listed in the source files is also my PayPal account. But there's no need for that!

**Comment by alberttwong** [comment]
Not sure if you're aware but paypal now charge money to send money.   Do you have venmo?
