### ISSUE TITLE
Help with Flashing Netgear r6220

### ISSUE THREAD

**Issue by knowmansoul** [jclehner/nmrpflash#24]
I'm noob and bricked the router with the wrong bin file and now I am having trouble recovering. 
Following the instructions and a lot of trial and error, I am not certain what have done wrong and/or right. Into hour 6 and going to shutdown for now. I am working on windows machine, but, could switch to a Ubuntu distro on a laptop, if that is a better way to flash the OEM firmware back.

**Comment by jclehner** [comment]
1. Move your firmware file to the same directory as `nmrpflash.exe`
2. Open a [command prompt with administrator privileges](https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/).
3. Switch to the directory where `nmrpflash.exe` and your firmware file are located. For example, if they are in a folder called `flash` on your Desktop, run the following command: `cd C:\Users\<YOUR USERNAME>\Desktop\flash`

4. Turn off the router, and connect it your computer using a network cable.
5. In the command prompt, run `nmrpflash -L`.
6. You'll get a list of network interfaces, named `netX`. Identify your Ethernet connection, for example `net3`.
7. Run `nmrpflash -i net3 -f "<YOUR FIRMWARE FILE NAME>"`
8. Turn on the router, and flashing should commence.

**Comment by MartinRousselle** [comment]
hi knowmansoul 
do you know what binary you used to corrupt your router ?

**Comment by megarage** [comment]
I fixed this issue easy just add .\\ and then nmrpflash -i net3 -f "<YOUR FIRMWARE FILE NAME>
so should be
.\\nmrpflash -i net3 -f "<YOUR FIRMWARE FILE NAME> I hope it helps
