### ISSUE TITLE
Writing to routing socket: No such process

### ISSUE THREAD

**Issue by adampatarino** [jclehner/nmrpflash#25]
From MacOS I'm attempting to flash my netgear r7000, but am having issues connecting to make the transfer. Here's my latest command and logs:

```
sudo ./nmrpflash -v -i en10 -A 10.0.0.4 -a 10.0.0.250 -f dd-wrt.K3_R7000_mod.chk
```
This returns an error:
```
Adding 10.0.0.4 to interface en10.
Advertising NMRP server on en10 ... -
Received configuration request from cc:40:d0:0a:16:dd.
Sending configuration: 10.0.0.250/24.
arp: writing to routing socket: No such process
arp: 10.0.0.250: No such process
arp: writing to routing socket: No such process
arp: 10.0.0.250: No such process
```
My Router is using 10.0.0.1 for the network's IP and I've reserved 10.0.0.4 for my computer.

<img width="626" alt="Screen Shot 2020-02-09 at 2 39 22 PM" src="https://user-images.githubusercontent.com/4479915/74108600-03b3ce80-4b4a-11ea-83ad-e86ad66b8834.png">

Any ideas?

**Comment by jclehner** [comment]
Try running `nmrpflash` without the `-a` and `-A` switches. You shouldn't need to specify them, unless in certain special circumstances.

**Comment by adampatarino** [comment]
Well - I was getting an error message, which is why I tried to assign the IPs in the first place.

Running 
```
sudo ./nmrpflash -v -i en10 -f dd-wrt.K3_R7000_mod.chk
```

Gives me:
```
Adding 10.164.183.253 to interface en10.
Advertising NMRP server on en10 ... -
Received configuration request from cc:40:d0:0a:16:dd.
Sending configuration: 10.164.183.252/24.
delete: cannot locate 10.164.183.252
Timeout while waiting for TFTP_UL_REQ.
10.164.183.252 (10.164.183.252) deleted
```

**Comment by jclehner** [comment]
The `delete: cannot locate 10.164.183.252` is expected, as this address usually does not have an ARP entry. An ARP issue would cause problems with the TFTP upload, but this is not the case here: `nmrpflash` waits for the router to send a TFTP upload request, before attempting the upload, but this request never arrives. Not exactly sure as to why.

How did you connect the router to your Mac?

**Comment by adampatarino** [comment]
I have a usb-c to Ethernet adapter and turned off WiFi

**Comment by jclehner** [comment]
Hmm... Can you try running `tcpdump -i en10 -w dump.pcap` while using `nmrpflash` (without `-a` and `-A`), and then send me the dump file via email?

**Comment by adampatarino** [comment]
Hey @jclehner thanks for all your support. I ended up just replace the router - I was getting too frustrated with all the work arounds just to get it to function correctly. I'll close this thread, but thank you for all your help!
