### ISSUE TITLE
Donation options?

### ISSUE THREAD

**Issue by issmirnov** [jclehner/nmrpflash#28]
Hey @jclehner - this utility saved my ass when I bricked a friend's router. I would love to send a little love your way - can you send up a donate link?

I've heard good things about https://www.buymeacoffee.com/, and I'm sure there are other platforms out there. Keep us posted.

**Comment by FrostKnight** [comment]
Saved my ass too, I hard bricked my router and this literally saved me!

**Comment by jclehner** [comment]
Glad it helped. Here you go: https://www.buymeacoffee.com/jclehner
Closing this now, as I've added a link in the README.md.
Thanks!

**Comment by FrostKnight** [comment]
> Glad it helped. Here you go: https://www.buymeacoffee.com/jclehner
> Closing this now, as I've added a link in the README.md.
> Thanks!

Refer to here for what I donated: 

https://github.com/jclehner/nmrpflash/issues/30#issuecomment-626991190

**Comment by issmirnov** [comment]
@jclehner thank you very much!
