### ISSUE TITLE
Works great with Netgear R6220

### ISSUE THREAD

**Issue by hqvv** [jclehner/nmrpflash#3]
Just for record, not a real issue.
Many thanks for your great works, your tool helps to unbricked my Netgear R6220 just now.
The device comes with a nand flash, it is not possible for me to recover it without this tool.

[NMRP_R6220.txt](https://github.com/jclehner/nmrpflash/files/836323/NMRP_R6220.txt)

**Comment by jclehner** [comment]
Thanks for the feedback!

**Comment by emersion** [comment]
@hqvv Can you describe how you managed to unbrick your device? I'm in the same situation as you, but I have issues flashing my router: #4

**Comment by laktak** [comment]
fyi: I wasn't able to use this on OSX with the R6220:

```
$ ./nmrpflash -vvv -i en4 -f R6220_FW_V1.1.0.34_1.0.1/R6220_V1.1.0.34_1.0.1.img
Adding 10.164.183.253 to interface en4.
Advertising NMRP server on en4 ... /Unexpected packet length (expected 20, got 60).
```

The same command on Windows worked just fine.

**Comment by jclehner** [comment]
@laktak Did you use the same version on OSX as on Windows? The `Unexpected packet length` message is not found in the latest release (`v0.9.11-rc1`).

**Comment by laktak** [comment]
@jclehner yes, I used `nmrpflash-0.9.11-rc1-osx.zip`.

**Comment by jclehner** [comment]
Strange... This issue should be fixed in the upcoming release though.
