### ISSUE TITLE
Netgear WNDR3800 works great thanks to you

### ISSUE THREAD

**Issue by FrostKnight** [jclehner/nmrpflash#30]
today I bricked one for reasons of dumbness, and your software unbricked it for me.  
I wonder if anyone has used this to unbrick the china version of this router.
Anywho, thanks a lot! 

I appreciate it, thank you! 

I used this, 

nmrpflash -i eth0 -f EX2700-V1.0.1.8.img

Albeit my way of doing it was different due to the operating system being a bit odd, 

eth0 was replaced with enp0s25, but yeah, I use a very niche linux distro so yeah.

Please add this to the list of supported routers for your software, I am sure other people will want to know. :)

**Comment by jclehner** [comment]
Thanks, I'll update the readme accordingly. `enp0s25` isn't that odd for distros using `systemd`. I I just used `eth0` as a portable example, if there's even such a thing ;)

**Comment by FrostKnight** [comment]
appreciated! What's even more amazing is that it was a hard brick. Also, it is odd, because I wasn't using systemd. Either way, you saved me 30-40$
So can I donate some money to you? I am not rich, but I will send at least a fraction of it to you, (10$ at least)
Anyways thank you!

**Comment by FrostKnight** [comment]
Since you were so helpful, I got you three coffees, enjoy!
