### ISSUE TITLE
Netgear D6220

### ISSUE THREAD

**Issue by NO-ob** [jclehner/nmrpflash#38]
I used the tool successfully on the D6220 with a .chk file from the netgear site. Used V1.0.0.16_1.0.16 because the newer fw file was too big(36mb)

The flash command need to be run twice first time prints 
```Timeout while waiting for TFTP_UL_REQ.```
Then on the second time it works correctly

**Comment by jclehner** [comment]
Some devices are pretty picky when it comes to timing. Glad it worked!
