### ISSUE TITLE
Application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by Owen000** [jclehner/nmrpflash#40]
after trying to install this on my windows computer the first error I got was wpcap.dll was not found. I reinstalled npcap and that also didn't work. I looked it up and installed wpcap.dll from a website. Once I put wpcap.dll in the folder I ran nmrpflash again and got the Application was unable to start correctly (0xc000007b) error. Any suggestions?

**Comment by jclehner** [comment]
Don't just download `.dll` files from the internet. In the best case, it's the wrong one, in the worst case it's malicious software which, in the case of `nmrpflash` runs with administrator privileges!

> I reinstalled npcap and that also didn't work.

What happened? What was the error message?

**Comment by Owen000** [comment]
There was no error message reinstalling npcap. The error message was running npmrflasb

**Comment by jclehner** [comment]
> The error message was running npmrflasb

What was the exact error message? Please post the _whole_ output after running `nmrpflash` with `-vvv`!

**Comment by Owen000** [comment]
![Annotation 2020-07-08 103246](https://user-images.githubusercontent.com/67721175/86938757-6237a580-c106-11ea-8eb4-16aef2d01ec0.png)

**Comment by jclehner** [comment]
If you delete `wpcap.dll` (the one you downloaded) from the directory where `nmrpflash.exe` is located, and reinstall [Npcap](https://nmap.org/npcap/dist/npcap-0.9994.exe), do you get the same error message?

**Comment by Owen000** [comment]
oops looked like I had an outdated version of npcap. Thanks for the help!

**Comment by codypaternostro** [comment]
I needed to have this box checked during installation! I was troubleshooting for the first time, so I figured I would add this here for others.
![install_API_mode](https://github.com/user-attachments/assets/7cc6f7f3-77b9-4b38-bd73-997fc1901df0)
