### ISSUE TITLE
Cannot flash on r8000

### ISSUE THREAD

**Issue by ohua28** [jclehner/nmrpflash#41]
Router off 
Run nmrpflash
router on 

Result: 
D:\>nmrpflash -i net9 -f R8000-V1.0.4.56_10.1.71_BETA.chk -vv
net9: \Device\NPF_{346FE1D0-935B-4DCB-B431-660800195026}
Adding 10.164.183.253 to interface net9.
Failed to bind after 5 seconds: bind: The requested address is not valid in its context.

Router on
Run nmrpflash
router off and on 

result:
D:\>nmrpflash -i net9 -f R8000-V1.0.4.56_10.1.71_BETA.chk -vv
net9: \Device\NPF_{346FE1D0-935B-4DCB-B431-660800195026}
Adding 10.164.183.253 to interface net9.
Advertising NMRP server on net9 ... -
Received configuration request from 9c:3d:cf:5c:2c:06.
Sending configuration: 10.164.183.252/24.
Timeout while waiting for TFTP_UL_REQ.

**Comment by ohua28** [comment]
hmm works like charm i run the command twice

D:\>nmrpflash -i net4 -a 192.168.1.1 -f R8000-V1.0.4.56_10.1.71_BETA.chk -vv
net4: \Device\NPF_{346FE1D0-935B-4DCB-B431-660800195026}
Advertising NMRP server on net4 ... |
Received configuration request from 9c:3d:cf:5c:2c:06.
Sending configuration: 192.168.1.1/24.
Timeout while waiting for TFTP_UL_REQ.

D:\>nmrpflash -i net4 -a 192.168.1.1 -f R8000-V1.0.4.56_10.1.71_BETA.chk -vv
net4: \Device\NPF_{346FE1D0-935B-4DCB-B431-660800195026}
Advertising NMRP server on net4 ... \
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Using remote filename 'R8000-V1.0.4.56_10.1.71_BETA.chk'.
Uploading R8000-V1.0.4.56_10.1.71_BETA.chk ... OK
Waiting for remote to respond.
Received keep-alive request (29).
Remote finished. Closing connection.
Reboot your device now.

**Comment by mozilla2012** [comment]
For future people who Google and find this thread:

I was seeing this error:
`bind: The requested address is not valid in its context`

To fix this, I added these args to my command:
`-a 192.168.1.1 -A 192.168.1.2`
(Those are the addresses I was using for my laptop and router.)

Then things worked for me.
