### ISSUE TITLE
Success with R8000

### ISSUE THREAD

**Issue by coopstev** [jclehner/nmrpflash#43]
Hi. I just wanted to let you know that this just worked with my NETGEAR R8000 AC3200 Nighthawk router. There was one notable difference from your described steps though: the router had to be on when I ran the command. I had to plug into Ethernet 4 on the router and power it on, then wait until the power light was solid amber before running the command. Thanks so much for the awesome tool!

**Comment by jclehner** [comment]
Thanks, I've updated the readme accordingly!
