### ISSUE TITLE
Timeout while waiting for TFTP_UL_REQ.

### ISSUE THREAD

**Issue by pitosalas** [jclehner/nmrpflash#44]
~/Downloads sudo nmrpflash -i en0 -f R6700v3-V1/x.chk
Advertising NMRP server on en0 ... /
Received configuration request from cc:40:d0:8b:0c:6a.
Sending configuration: 10.164.183.252/24.
delete: cannot locate 10.164.183.252
Timeout while waiting for TFTP_UL_REQ.
10.164.183.252 (10.164.183.252) deleted

This is on a Mac, with a bricked NetFear R6700V3.

**Comment by jclehner** [comment]
Have you tried [these instructions](https://github.com/jclehner/nmrpflash/blob/master/README-R7000.md) as well?

**Comment by pitosalas** [comment]
Something along those lines. I just tried it a few times, with combinations of reboot etc. And it worked!

Mysterious timing stuff.

Anyway, I have my router back!

Pito Salas
Brandeis Computer Science
Volen 134
