### ISSUE TITLE
Success with R8500

### ISSUE THREAD

**Issue by jeff-anttila** [jclehner/nmrpflash#49]
Similar to coopsteve’s comment two weeks ago, I found success with a Netgear R8500 AC5300 (Nighthawk X8).

I used the pre-compiled 0.9.14 MacOS distribution.  There was a MacOS Catalina permissions/gatekeeper issue which I’ve run into frequently with un-signed code.  To help others, maybe it’d be worthwhile adding these tips/steps to allow execution.  Feel free to cut and paste these steps into any release docs.

This is resolved by going to System Preferences, selecting “Security & Privacy options, and select the “General” tab.  3/4 of the way down the window, there’s a message “nmrpflash”was blocked from opening because it’s not from an identified developer.    Press “Open Anyway” button to the left of the error and your good to go. 

One issue though.  The R8500 has dual gigabit WAN interfaces which may be a factor... could it actually be user error..?  The tool would terminate with an error.  However, a subsequent execution would resume/start the TFTP process.

I’m assuming that it successfuly sends the magic packet to place it in tftp mode, but because I can’t determine the root cause, I’ll share the logs belowZ. What could it be..?  

Still, it worked..!

Thanks for writing this utility, and breathing life back into a router I thought was a heavy doorstop!  

## Execution#1 

>sh-3.2# ./nmrpflash -i en0 -f R8500-V1.0.2.134_1.0.99.chk -vvv
Adding 10.164.183.253 to interface en0.
Advertising NMRP server on en0 ... \
Received configuration request from a0:04:60:8e:49:08.
Sending configuration: 10.164.183.252/24.
delete: cannot locate 10.164.183.252
Timeout while waiting for TFTP_UL_REQ.
10.164.183.252 (10.164.183.252) deleted

## Execution#2: (within 3 seconds)

>sh-3.2# ./nmrpflash -i en0 -f R8500-V1.0.2.134_1.0.99.chk -vvv
Adding 10.164.183.253 to interface en0.
Advertising NMRP server on en0 ... -
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Using remote filename 'R8500-V1.0.2.134_1.0.99.chk'.
Uploading R8500-V1.0.2.134_1.0.99.chk ... << WRQ(R8500-V1.0.2.134_1.0.99.chk, octet)
 ACK(0)
 DATA(1)
ACK(1)
...
OK
Waiting for remote to respond.
Received keep-alive request (27).  
Remote finished. Closing connection.
Reboot your device now.

**Comment by jclehner** [comment]
Thanks for the feedback!
