### ISSUE TITLE
R6220 unable to flash

### ISSUE THREAD

**Issue by gardiol** [jclehner/nmrpflash#52]
I have somehow bricked a new 6220 router by flashing openwrt img file from the web GUI (original firmware) so i amtrying nmrpflash to unbrick it. 

I have downloaded latest stock IMG from netgear support page.

This is what i get:

```
WillyPC /home/willy/Downloads #  ./ww/nmrpflash-master/nmrpflash -i enp0s20f0u2 -f R6220_V1.1.0.100_1.0.1.img
Advertising NMRP server on enp0s20f0u2 ... -
Received configuration request from 14:59:c0:ce:00:58.
Sending configuration: 10.164.183.252/24.
Received upload request without filename.
Uploading R6220_V1.1.0.100_1.0.1.img ... OK
Waiting for remote to respond.
Timeout while waiting for 0000.
```

Any suggestions? 

The router of course does not boot.

**Comment by jclehner** [comment]
While you're seeing "Waiting for remote to respond.", watch for changes in the router's leds. Is possible that the flashing takes longer than the timeout. Just to be sure, wait for around 15 minutes until you reboot the router!

**Comment by gardiol** [comment]
Yes! Adding "-T 900" to the command line did the trick! Thank you.

I think this should be noted in the README and the error message cited as well as the others... It would have saved me time and worries!
