### ISSUE TITLE
R6220 not getting past "advertising NMRP server"

### ISSUE THREAD

**Issue by chippey5** [jclehner/nmrpflash#53]
I have a working openWRT installation on my R6220, but I wish to revert to the stock image. 

I started off following the official [openWRT unbricking guide for the R6220](https://openwrt.org/toh/netgear/netgear_r6220) and checking [this closed issue](https://github.com/jclehner/nmrpflash/issues/11) to this tool, connecting the computer to the**LAN1** port on the router and disconnecting all other cables. For some reason, I just can't get past the `No response after 60 seconds. Bailing out.` part.

Now I've tried the following:

`sudo ./nmrpflash -i eno2 -f R6220_V1.1.0.100_1.0.1.img -vv`
`sudo ./nmrpflash -i eno2 -f R6220_V1.1.0.100_1.0.1.img -a 192.168.1.1 -A 192.168.1.2 -vv`
`sudo ./nmrpflash -i eno2 -f R6220_V1.1.0.100_1.0.1.img -a 192.168.2.1 -A 192.168.2.2 -vv`
`sudo ./nmrpflash -i eno2 -f R6220_V1.1.0.100_1.0.1.img -a 192.168.1.1 -A 192.168.1.2 -m *mac_address_hidden* -vv`

Both after and before resetting openWRT to default settings. I'm working with a /24 subnet and the router's IP is 192.168.1.1 by default. I also tried setting the computer's IP statically to _192.168.1.2_ and redoing all these commands, to no avail. Am I missing something or there something else I can try?

**Comment by jclehner** [comment]
Can you start a `tcpdump` before running `nmrpflash`? I.e. something like:

$ sudo tcpdump -i eno2 -w nmrpflash.pcap

And then send the resulting file via email?

**Comment by chippey5** [comment]
I'm very sorry for the delay. I've had a good experience with openWRT since after I raised this issue. Given that I don't want to fix something that isn't broken, I'm going to close this issue for now. If I decide to get a new router in the future, I will give this a shot again for the sake of potential bugfixing.

**Comment by wretchey** [comment]
Guy can anyone please help. I’m unable to pass No response after 60 seconds. Bailing out
