### ISSUE TITLE
Adding a switch between router and computer helped

### ISSUE THREAD

**Issue by ECGemini** [jclehner/nmrpflash#54]
First of all, THANK YOU for such a great tool!

I am trying to debrick a Netgear R8500. As recommended I connected my Windows 10 laptop directly to the ethernet port 1 on the router. I kept getting the same error “_**Failed to bind after 5 seconds: bind: The requested address is not valid in its context**_” as soon as starting the nmrpflash command. I already manually set my computer IP address 192.168.1.10, but still cannot get pass this error.
I was about to give up on nmrpflash when I came across this article: [openWRT unbricking guide for the R6220](https://openwrt.org/toh/netgear/netgear_r6220), in which it was mentioned `**For Windows users, ethernet cable must be connected to a switch or nmrpflash would fail to operate.**` 
So I decided to give it a try out of desperation. Added a switch between the laptop and the router, BOOM! “Advertising NMRP server on enet…” started. I don’t know why adding a switch made such a big difference or why it only applies to Windows users but apparently enough of other people have found this tip useful. You might want to consider adding it in your README.

I found keeping a separate DOS window open with “ping 192.168.1.1 -t” running pretty handy in helping me to decide on the timing of when to start the nmrpflash command. Since the router is in a boot loop, there is infinite chances for you to try. The most reliable moment for me to start nmrpflash command is when all lights go out, so that the program is advertising when the router starts to respond to the ping. 

Also I found that I always have to try the command twice in order to upload the firmware. The first try always timeout even when the connection is established, but all I have to do is use up arrow to rerun the command immediately after the first error. Works every time.

Sample log below:
================================================
C:\Users\eric_\Downloads>nmrpflash -i net0 -f R8500-V1.0.2.134_1.0.99.chk
Advertising NMRP server on net0 ... |
Received configuration request from 50:6a:03:b3:c7:12.
Sending configuration: 10.164.183.252/24.
Timeout while waiting for TFTP_UL_REQ.
 
C:\Users\eric_\Downloads>nmrpflash -i net0 -f R8500-V1.0.2.134_1.0.99.chk
Advertising NMRP server on net0 ... \
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Uploading R8500-V1.0.2.134_1.0.99.chk ... OK
Waiting for remote to respond.
Received keep-alive request (31).
Remote finished. Closing connection.
Reboot your device now.

**Comment by ECGemini** [comment]
Quick update after a lot of trials and experiments. After I mastered the timing of nmrpflash through a switch, I went back to directly connecting the ethernet cable to the router and try to see if I can get it working without the switch. This time I know when to start and what to expect so I can experiment with much higher confidence. It does work, though timing is critical!

I believe the main confusion came from the instructions “**First of all, turn off the router. Then start nmrpflash using the following command: As soon as you see the Advertising NMRP server message, turn the router on.**” In my case, if I have the router turned off, I will never see the “Advertising NMRP server” message no matter how long I wait or how many times I try, because it always error out immediately. “Failed to bind after 5 seconds: bind: The requested address is not valid in its context”.

The proper procedure should be, at least in my case: 
**Turn on the router, then immediately start nmrpflash command,** only when the router is on you can have a chance to get the “Advertising NMRP server” message. You might still get the “Failed to bind after 5 seconds” error if the router is not ready to receive firmware yet, don’t worry, just repeat the same command immediately and keep trying, by the time you see router response to ping “Reply from 192.168.1.1: bytes=32 time=32ms TTL=100”, the NMRP handshake would start.

It is my theory that the nmrpflash looks for some kind of response before advertising NMRP, so having the router turned on is critical. That would also explain why adding a switch helped, because the switch produced some network response when router was off which allowed the nmrpflash to start advertising without the router, which expanded the opportunity window.

Hope that helps.

**Comment by jclehner** [comment]
Thanks for the info! The IP and ARP handling is somewhat flawed in the current release. A new release is planned, but COVID keeps me busy otherwise!

**Comment by L31FY** [comment]
My R6700v2 bricked a few times and this seems to be a Windows exclusive issue. I have had no issues using Lubuntu and the terminal and the Linux build. None of the weird errors happen there.

**Comment by jclehner** [comment]
The latest release (`0.9.15-rc3`) should fix the `Failed to bind after 5 seconds` issue. It would be great if anyone here could take the time to verify this!

**Comment by ECGemini** [comment]
Took me a while to get the test environment set up exactly as it was before due to the holidays. Once everything is put back in place, the test ran very smoothly. Yes, I no longer see the "Failed to bind after 5 seconds" error, even when running nmrpflash with router powered off, it would immediately "Advertising NMRP server" and would wait for the router response. This makes it very easy to catch the router boot request.  @jclehner Good job!

**Comment by ECGemini** [comment]
I believe my original issue can be closed with the new release 0.9.15-rc3.
