### ISSUE TITLE
Cannot Flash WNDR3400v2

### ISSUE THREAD

**Issue by alexacallmebaka** [jclehner/nmrpflash#55]
I am trying to flash the official Netgear firmware back on a Netgear WNDR3400v2 router after a bad OpenWRT flash in order to unbrick it. I am running the following command: `./nmrpflash -i enx00e04c0311dc -f WNDR3400v2-V1.0.0.54_1.0.82.chk -vvv` nad am met with the following logs: 
```
Adding 10.164.183.253 to interface enx00e04c0311dc.
Advertising NMRP server on enx00e04c0311dc ... -
Received configuration request from 2c:b0:5d:2b:48:e1.
Sending configuration: 10.164.183.252/24.
rtnl_neigh_delete: Object not found
Timeout while waiting for TFTP_UL_REQ.
```

If it means anything, I also tried this version of the command: `/nmrpflash -i enx00e04c0311dc -f WNDR3400v2-V1.0.0.54_1.0.82.chk -vvv -a 192.168.1.1 -A 192.168.1.10` but received the same output (different ips of course). I am on Debian 10 and hooked up to the router using a thunderbolt 3 to Ethernet adapter, and an Ethernet cable.

I honestly have no clue what I'm doing with this stuff, as I'm  complete newbie. Any help would be greatly appreciated!

**Comment by jclehner** [comment]
Have you tried [these instructions](https://github.com/jclehner/nmrpflash/blob/master/README-R7000.md) already?

**Comment by alexacallmebaka** [comment]
Those instructions would not have helped because I could not get to the web interface. That and the router had a bad flash of OpenWRT and not Netgear firmware. I was able to recover the router using serial recovery and TFTP.
