### ISSUE TITLE
R8000 no success

### ISSUE THREAD

**Issue by v01der** [jclehner/nmrpflash#58]
not connected to the router in either ways but i have access through http://192.168.1.1 but cant able to update firmware there too
![r8000_2](https://user-images.githubusercontent.com/73497180/97220321-4ceba180-17f1-11eb-98a6-a35151ddf8b9.jpg)

**Comment by jclehner** [comment]
Check out #41, #43, and [this](https://github.com/jclehner/nmrpflash/blob/master/README-R7000.md).
