### ISSUE TITLE
I don't understand the user guide

### ISSUE THREAD

**Issue by martinboson** [jclehner/nmrpflash#60]
ok let's see here...

1)

>Next, you'll have to determine which network interface corresponds to the one connected to the Netgear router. All available interfaces can be listed using

># nmrpflash -L

frome where? I'm on windows 10 and opening nmrpflash.exe doesn't allow me to run commands. it just says "press any key to exit" then shuts down if you try typing something. 
opening the "cmd" tool doesn't recognize # nmrpflash -L as a valid command. Soooooo... FROM WHERE? 

2)

>First of all, turn off the router. Then start nmrpflash using the following command:

># nmrpflash -i eth2 -f EX2700-V1.0.1.8.img
Advertising NMRP server on eth2 ... /

FROM.
WHERE?

**Comment by jclehner** [comment]
https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt
