### ISSUE TITLE
Failed to bind after 5 seconds

### ISSUE THREAD

**Issue by martinboson** [jclehner/nmrpflash#61]
I tried running the command 

nmrpflash -i eth2 -f openwrt-19.07.4-brcm47xx-mips74k-netgear-wndr3400-v3-squashfs.chk

got the error:

Invalid interface alias.

**Comment by martinboson** [comment]
I changed from eth2 to net8 (that's what -L command tells me my ethernet port is)

c:\>nmrpflash -i net8 -f openwrt-19.07.4-brcm47xx-mips74k-netgear-wndr3400-v3-squashfs.chk
\Device\NPF_Loopback is not an ethernet interface.

what?

**Comment by martinboson** [comment]
new error: 
Failed to bind after 5 seconds: bind: The requested address is not valid in its context.

**Comment by Finni123** [comment]
I have the exact same problem, did you solve it somehow?

**Comment by jclehner** [comment]
@Finni123, @martinboson Please try the version below.

[nmrpflash-0.9.15-rc2-win32.zip](https://github.com/jclehner/nmrpflash/files/5683629/nmrpflash-0.9.15-rc2-win32.zip)
