### ISSUE TITLE
Error (3): Transfer cancelled

### ISSUE THREAD

**Issue by brewer-michael** [jclehner/nmrpflash#66]
First of all, thank you so much for putting this together. Your utility is the only thing that has worked for me to communicate with my router after Netgear's firmware update bricked it.

Everything appears to be working, though I have to re-run the command after an initial timeout from the router. Once I do the file transfer process starts, and then throws this error: Error (3): transfer cancelled

At first I thought I maybe had a bad firmware update file, but after trying several other versions from netgear I get the same error. Any ideas on what is causing the transfer to fail?

**Comment by jclehner** [comment]
What's the exact model?

**Comment by brewer-michael** [comment]
It's the R6700v3 (AC-1750)

**Comment by brewer-michael** [comment]
To follow up, I've tried adjusting the timeout settings when running nmrpflash, and the router gets into a loop where it requests and receives configuration over and over. I let it run overnight and it never got out of the loop. Also, I hooked up a serial connection and attempted to access it that way, but when I power on the router with the serial connection active the router doesn't appear to attempt to boot. All the lights light up steady and never turn off, and nothing appears in the serial console. I'm wondering if this router just isn't beyond hope at this point. Below is the text dialog from the loop it was in.

`Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 14:59:c0:ac:24:b8.
Sending configuration: 10.164.183.252/24.
Received CONF_REQ while waiting for TFTP_UL_REQ!
Received configuration request from 14:59:c0:ac:24:b8.
Sending configuration: 10.164.183.252/24.`

**Comment by junglejim1996** [comment]
I have the exact same model Negear router and am having the exact same issue

**Comment by jclehner** [comment]
Please try [this file](https://file.io/2QjUQwWDdhlg) instead. It's the latest firmware for this device (`V1.0.4.106_10.0.80`), but has been modified to use the next higher version number (`V1.0.4.106_10.0.81`), in case your bootloader rejects images with the same version number.

**Comment by brewer-michael** [comment]
Eureka! Router functionality fully restored. Thanks so much for digging into this! I was sure this thing was a goner. For reference, here's the readout on the successful transfer:

```.\nmrpflash -i net14 -f R6700v3-V1.0.4.106_10.0.81.chk
Advertising NMRP server on net14 ... |
Received configuration request from 14:59:c0:ac:24:b8.
Sending configuration: 10.164.183.252/24.
Received upload request without filename.
Uploading R6700v3-V1.0.4.106_10.0.81.chk ... Warning: TFTP block rollover. Upload might fail!
OK
Waiting for remote to respond.
Received keep-alive request (45).
Remote finished. Closing connection.
Reboot your device now.```

**Comment by timrhaynes** [comment]
I am having the same problem. The modified file that you supplied, is no longer on file.io. Can you please supply it again? Thank you!

**Comment by jclehner** [comment]
[Here](https://drive.google.com/file/d/1K0euAbsJWN_uKFxOom_pk8-XA0dtPFIZ/view?usp=sharing) you go, @timrhaynes . This is the current version, `1.0.4.120_10.0.91`, masquerading as `1.0.4.120_10.0.92`.

**Comment by timrhaynes** [comment]
Thank you very much!! :-D

**Comment by maxiolin** [comment]
Hi @jclehner, would you mind sharing a guide on how to change the version of the chk file.
Thank you.

**Comment by liqili** [comment]
Hi @jclehner, how can I update the version number of the firmware. I got the same situation for my router R6250.

**Comment by Robibedo** [comment]
> @maxiolin @liqili
> 
> https://github.com/jclehner/patchchk

Windows defender identifies the downloaded tool as a virus! is it a false positive?

**Comment by simonsayshi** [comment]
@jclehner hello, thanks you for posting/helping with it! I have exact same issue and model, can you help post the new file? thank you so much in advance!

**Comment by pejterpal** [comment]
@jclehner would you be so kind and create another masqueraded firmware file?
Im not sure how to use the patchck to create my own
