### ISSUE TITLE
nmrpflash: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by LimestoneBob** [jclehner/nmrpflash#67]
Running sh nmrpflash ( prebuilt binary 0.9.14 ) in linux kernel 5.4.0-58-generic on Ubuntu 20.04 results in error: 

nmrpflash: 1: Syntax error: "(" unexpected

**Comment by jclehner** [comment]
Running `sh nmrpflash` won't work, as it isn't a shell script. Use `./nmrpflash` instead!

**Comment by LimestoneBob** [comment]
Yes, that works. Thank you.

**Comment by jclehner** [comment]
Try specifying your router's MAC address using `-m xx:xx:xx:xx:xx:xx`. It should be printed on the router's label.

**Comment by LimestoneBob** [comment]
Yes, I'm now able to see NETGEAR admin setup. Thank you.

me@me-ThinkPad-T440s:~/srv$ sudo ./nmrpflash -i enp0s25 -m B0:39:56:19:9A:A2 -f R6120v1.76.img
[sudo] password for me: 
Waiting for phyiscal connection.
Advertising NMRP server on enp0s25 ... -
Received configuration request from 00:00:00:00:00:00.
Sending configuration: 10.164.183.252/24.
Received upload request without filename.
Uploading R6120v1.76.img ... OK
Waiting for remote to respond.
Received keep-alive request (6).  
Remote finished. Closing connection.
Reboot your device now.
