### ISSUE TITLE
Is the dd-wrt version you provided still recommended? 

### ISSUE THREAD

**Issue by awerni** [jclehner/nmrpflash#68]
The dd-wrt documentation (https://wiki.dd-wrt.com/wiki/index.php/Netgear_R7000) cites you as a provider of the latest firmware for the Netgear R7000. This version is already almost 2 yo. 
What do you recommend for my R7000? Is your dd-wrt version still ok or is there another more recent update? (maybe even OpenWRT).
I am suffering form poor Wifi performance and the lack of updates since Kong's departure.

**Comment by jclehner** [comment]
I didn't *recommend* that DD-WRT build, I just provided it to fix an issue a user was having. Personally, I'd prefer OpenWRT, and the R7000 is indeed supported ([download link](https://downloads.openwrt.org/releases/19.07.5/targets/bcm53xx/generic/)). These images should be flashable without modification.

**Comment by awerni** [comment]
Thanks for your suggestion. The OpenWRT R7000 page (https://openwrt.org/toh/netgear/r7000) lists Wifi as unsupported function (2.4GHz partly, 5GHz fully) for this router. Is this list up-to-date? My neighbours are using all channels in the 2.4GHz range. Presumably I get better throughput by using the 5GHz channels. Any hints that 2.4GHz and 5GHz might work?

**Comment by jclehner** [comment]
> The OpenWRT R7000 page [...] lists Wifi as unsupported function (2.4GHz partly, 5GHz fully) for this router.

True, I missed that. 

> The dd-wrt documentation [...] cites you as a provider of the latest firmware for the Netgear R7000. This version is already almost 2 yo.

In the dd-wrt router database [entry for this device](https://dd-wrt.com/support/router-database/?model=R7000_v1) I'm seeing an image from November 2020. Doesn't this `.chk` image work with your device?

**Comment by awerni** [comment]
I tried dd-wrt build 44715 from last November and it seems to work pretty well. I can reach 97Mbits/sec via Wifi and around 340 Mbits/sec via cable within my network. It's better than it used to be (~60Mbits/sec for Wifi). Thanks for the hint.

**Comment by jclehner** [comment]
You're welcome! Closing this now.
