### ISSUE TITLE
No changes after reboot

### ISSUE THREAD

**Issue by anand230999** [jclehner/nmrpflash#69]
I have tried many methods to unbrick my netgear r6220 router. My router got bricked while updating firmware. I have tried tftp method too, but no luck till now. I have connected with serial port to see what happens while doing nmrpflash. I got the attached responses from serial port while flashing.
![IMG_20201231_204337](https://user-images.githubusercontent.com/13768012/103415798-bd27f200-4ba9-11eb-9013-53ec79d61bf7.jpg)
![IMG_20201231_204310](https://user-images.githubusercontent.com/13768012/103415803-bf8a4c00-4ba9-11eb-9927-bfa9a0dfbab7.jpg)

**Comment by jclehner** [comment]
What messages do you get on the serial console when booting the device normally?

**Comment by anand230999** [comment]
It will boot and show some "bad block" errors and goes to tftp mode. While trying to flash using tftp I'm getting some image checksum errors in serial console. I tried different firmware version images.

**Comment by jclehner** [comment]
If the flash has too many bad blocks (which appears to be the case), then you won't be able to unbrick it unfortunately!

**Comment by anand230999** [comment]
This is the serial console log getting while booting





===================================================================
     		MT7621   stage1 code 13:15:05 (ASIC)
     		CPU=50000000 HZ BUS=16666666 HZ
==================================================================
Change MPLL source from XTAL to CR...
do MEMPLL setting..
MEMPLL Config : 0x11100000
3PLL mode + External loopback
=== XTAL-40Mhz === DDR-1200Mhz ===
PLL4 FB_DL: 0x10, 1/0 = 583/441 41000000
PLL2 FB_DL: 0x15, 1/0 = 656/368 55000000
PLL3 FB_DL: 0x18, 1/0 = 754/270 61000000
do DDR setting..[00320381]
Apply DDR3 Setting...(use customer AC)
          0    8   16   24   32   40   48   56   64   72   80   88   96  104  112  120
      --------------------------------------------------------------------------------
0000:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0001:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0002:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0003:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0004:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0005:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0006:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0007:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0008:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0009:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    1
000E:|    0    0    0    0    0    0    0    0    0    1    1    1    1    1    1    1
000F:|    0    0    0    0    1    1    1    1    1    1    1    1    1    1    0    0
0010:|    1    1    1    1    1    1    1    1    1    0    0    0    0    0    0    0
0011:|    1    1    1    0    0    0    0    0    0    0    0    0    0    0    0    0
0012:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0013:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0014:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0015:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0016:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0017:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0018:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0019:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001E:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001F:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
rank 0 coarse = 15
rank 0 fine = 72
B:|    0    0    0    0    0    0    0    0    0    0    1    1    1    0    0    0
opt_dle value:11
DRAMC_R0DELDLY[018]=00001D1E
==================================================================
		RX	DQS perbit delay software calibration 
==================================================================
1.0-15 bit dq delay value
==================================================================
bit|     0  1  2  3  4  5  6  7  8  9
--------------------------------------
0 |    15 12 14 14 15 11 15 11 6 12 
10 |    8 13 11 13 8 12 
--------------------------------------

==================================================================
2.dqs window
x=pass dqs delay value (min~max)center 
y=0-7bit DQ of every group
input delay:DQS0 =30 DQS1 = 29
==================================================================
bit	DQS0	 bit      DQS1
0  (0~58)29  8  (1~54)27
1  (1~56)28  9  (1~56)28
2  (1~58)29  10  (1~56)28
3  (1~57)29  11  (1~54)27
4  (1~57)29  12  (1~55)28
5  (1~59)30  13  (1~57)29
6  (0~58)29  14  (1~57)29
7  (1~60)30  15  (1~56)28
==================================================================
3.dq delay value last
==================================================================
bit|    0  1  2  3  4  5  6  7  8   9
--------------------------------------
0 |    15 14 15 15 15 11 15 11 8 13 
10 |    9 15 12 13 8 13 
==================================================================
==================================================================
     TX  perbyte calibration 
==================================================================
DQS loop = 15, cmp_err_1 = ffffba15 
DQS loop = 14, cmp_err_1 = ffff2a00 
dqs_perbyte_dly.last_dqsdly_pass[0]=14,  finish count=1 
DQS loop = 13, cmp_err_1 = ffff2a00 
DQS loop = 12, cmp_err_1 = ffff0800 
DQS loop = 11, cmp_err_1 = ffff0000 
dqs_perbyte_dly.last_dqsdly_pass[1]=11,  finish count=2 
DQ loop=15, cmp_err_1 = ffff01a0
DQ loop=14, cmp_err_1 = ffff0080
dqs_perbyte_dly.last_dqdly_pass[1]=14,  finish count=1 
DQ loop=13, cmp_err_1 = ffff0000
dqs_perbyte_dly.last_dqdly_pass[0]=13,  finish count=2 
byte:0, (DQS,DQ)=(8,8)
byte:1, (DQS,DQ)=(8,9)
20,data:88
[EMI] DRAMC calibration passed

===================================================================
     		MT7621   stage1 code done 
     		CPU=50000000 HZ BUS=16666666 HZ
===================================================================


U-Boot 1.1.3 (Oct 15 2014 - 11:40:56)

Board: Ralink APSoC DRAM:  128 MB
relocate_code Pointer at: 87fac000

Config XHCI 40M PLL 
Allocate 16 byte aligned buffer: 87fe1b50
Enable NFI Clock
# MTK NAND # : Use HW ECC
NAND ID [C2 F1 80 1D C2]
Device found in MTK table, ID: c2f1, EXT_ID: 801dc2
Support this Device in MTK table! c2f1 
select_chip
[NAND]select ecc bit:4, sparesize :64 spare_per_sector=16
Signature matched and data read!
load_fact_bbt success 1023
load fact bbt success
[mtk_nand] probe successfully!
mtd->writesize=2048 mtd->oobsize=64,	mtd->erasesize=131072  devinfo.iowidth=8
Env addr : 0x100000
.*** Warning - bad CRC, using default environment

============================================ 
Ralink UBoot Version: 4.2.1.0
-------------------------------------------- 
ASIC MT7621AS (MAC to MT7530 Mode)
DRAM_CONF_FROM: Auto-Detection 
DRAM_TYPE: DDR3 
DRAM bus: 16 bit
Xtal Mode=3 OCP Ratio=1/3
Flash component: NAND Flash
Date:Oct 15 2014  Time:11:40:56
============================================ 
icache: sets:256, ways:4, linesz:32 ,total:32768
dcache: sets:256, ways:4, linesz:32 ,total:32768 

 ##### The CPU freq = 880 MHZ #### 
 estimate memory size =128 Mbytes

Reset switch ...
#Reset_MT7530
set LAN/WAN LLLLW
..Example expects ABI version 2
Actual U-Boot ABI version 2

␛[31m******************************************
    Uboot StandAlone Entry
******************************************␛[0m
0, cmd
1, 0x0000000D
cmd : 0x0000000D


Press Ctrl+C to Enter the Main loop...
Example expects ABI version 2
Actual U-Boot ABI version 2

␛[31m******************************************
    Uboot StandAlone Entry
******************************************␛[0m
0, cmd
1, 0x0000000F
cmd : 0x0000000F
Enter NMRP_main
Flash Sector Number : 1024.
Bad block detected at 0xfc0000, oob_buf[0] is 0x0
NAND Section 3, has bad block at address bcfc0000, Image Offset fc0000
NAND Section 3, has bad block count 1
Bad block detected at 0x25e0000, oob_buf[0] is 0x0
NAND Section 5, has bad block at address be5e0000, Image Offset 25e0000
NAND Section 5, has bad block count 1
Bad block detected at 0x3680000, oob_buf[0] is 0x0
NAND Section 15, has bad block at address bf680000, Image Offset 3680000
NAND Section 15, has bad block count 1
Bad block detected at 0x3840000, oob_buf[0] is 0x0
NAND Section 16, has bad block at address bf840000, Image Offset 3840000
NAND Section 16, has bad block count 1
Bad block detected at 0x4040000, oob_buf[0] is 0x0
NAND Section 20, has bad block at address c0040000, Image Offset 4040000
NAND Section 20, has bad block count 1
Bad block detected at 0x46a0000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c06a0000, Image Offset 46a0000
NAND Section 21, has bad block count 1
Bad block detected at 0x6460000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c2460000, Image Offset 6440000
NAND Section 21, has bad block count 2
Bad block detected at 0x7ca0000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c3ca0000, Image Offset 7c60000
NAND Section 21, has bad block count 3

 NetTxPacket = 0x87FE5B00 

 KSEG1ADDR(NetTxPacket) = 0xA7FE5B00 

 NetLoop,call eth_halt ! 

 NetLoop,call eth_init ! 
Trying Eth0 (10/100-M)

 Waitting for RX_DMA_BUSY status Start... done


 ETH_STATE_ACTIVE!! 
NMRP_FLASH_SIZE_buffer --> a1000000.
NMRP:LISTENING
### No NMRP Server found ###
Example expects ABI version 2
Actual U-Boot ABI version 2

␛[31m******************************************
    Uboot StandAlone Entry
******************************************␛[0m
0, boot
Flash Sector Number : 1024.
Bad block detected at 0xfc0000, oob_buf[0] is 0x0
NAND Section 3, has bad block at address bcfc0000, Image Offset fc0000
NAND Section 3, has bad block count 1
Bad block detected at 0x25e0000, oob_buf[0] is 0x0
NAND Section 5, has bad block at address be5e0000, Image Offset 25e0000
NAND Section 5, has bad block count 1
Bad block detected at 0x3680000, oob_buf[0] is 0x0
NAND Section 15, has bad block at address bf680000, Image Offset 3680000
NAND Section 15, has bad block count 1
Bad block detected at 0x3840000, oob_buf[0] is 0x0
NAND Section 16, has bad block at address bf840000, Image Offset 3840000
NAND Section 16, has bad block count 1
Bad block detected at 0x4040000, oob_buf[0] is 0x0
NAND Section 20, has bad block at address c0040000, Image Offset 4040000
NAND Section 20, has bad block count 1
Bad block detected at 0x46a0000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c06a0000, Image Offset 46a0000
NAND Section 21, has bad block count 1
Bad block detected at 0x6460000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c2460000, Image Offset 6440000
NAND Section 21, has bad block count 2
Bad block detected at 0x7ca0000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c3ca0000, Image Offset 7c60000
NAND Section 21, has bad block count 3

***************************************************
    Sercomm Boot Version 1.16.0

***************************************************
Upgrade flag check failed, and upgrade flag is 0x0 ....Upgrade flag check failed, enter tftp recover
Welcome to TFTP Recovery mode!
Flash Sector Number : 1024.
Bad block detected at 0xfc0000, oob_buf[0] is 0x0
NAND Section 3, has bad block at address bcfc0000, Image Offset fc0000
NAND Section 3, has bad block count 1
Bad block detected at 0x25e0000, oob_buf[0] is 0x0
NAND Section 5, has bad block at address be5e0000, Image Offset 25e0000
NAND Section 5, has bad block count 1
Bad block detected at 0x3680000, oob_buf[0] is 0x0
NAND Section 15, has bad block at address bf680000, Image Offset 3680000
NAND Section 15, has bad block count 1
Bad block detected at 0x3840000, oob_buf[0] is 0x0
NAND Section 16, has bad block at address bf840000, Image Offset 3840000
NAND Section 16, has bad block count 1
Bad block detected at 0x4040000, oob_buf[0] is 0x0
NAND Section 20, has bad block at address c0040000, Image Offset 4040000
NAND Section 20, has bad block count 1
Bad block detected at 0x46a0000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c06a0000, Image Offset 46a0000
NAND Section 21, has bad block count 1
Bad block detected at 0x6460000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c2460000, Image Offset 6440000
NAND Section 21, has bad block count 2
Bad block detected at 0x7ca0000, oob_buf[0] is 0x0
NAND Section 21, has bad block at address c3ca0000, Image Offset 7c60000
NAND Section 21, has bad block count 3

 KSEG1ADDR(NetTxPacket) = 0xA7FE5B00 

 NetLoop,call eth_halt ! 

 NetLoop,call eth_init ! 
Trying Eth0 (10/100-M)

 ETH_STATE_ACTIVE!! 
Our ETH MAC:

a0  63  91  02  a1  48  
Enter TFTP_REC_wait4pkt

**Comment by jclehner** [comment]
As already stated, your flash appears to be bad. Since the bootloader is unable to correct this, it can't read/write firmware images. This is a hard brick unfortunately (unless you have the skills and tools to swap the flash chip).

**Comment by anand230999** [comment]
@jclehner Ok. Thanks for your help.
