### ISSUE TITLE
Error accessing file

### ISSUE THREAD

**Issue by brisims** [jclehner/nmrpflash#74]
Success on AC1000 WiFi Router (R6080), firmware version file R6080_V1.0.0.48.img
Followed steps directly, but got confused with file locations. Figured it out after using my brain a bit more 👍 

Thank you so much for saving my a** in the midst of working from home.

_Ignore below._ 

Resolution [Solved]:
**I put all 3 files on Desktop. I switched command prompt to desktop using cd C:\windows\users\MYNAME\desktop**
(I'm not sure if I can change the title of the issue)

---------
I received an 'error accessing file' message. 
Can you please provide some additional guidance on where all the files should be saved? e.g. the nmrpflash.exe, the npcap .exe, and the firmware .img?
Do I need to do anything with npcap or just install it?

It isn't very clear from the readme, and I'm a noob at this. Right now, I have all three files saved in C:\Windows\System32. As a non-admin command prompt, I was able to access desktop, but once I ran as admin, I could no longer access desktop so I just moved the files. (not sure if this is user error). 

When I use -f, I get 'error accessing file'. When I use -F, I get the full list of command options.

I'm on Windows 10 Home.

**Comment by jclehner** [comment]
Thanks for the feedback. Closing this now!
