### ISSUE TITLE
Address 192.168.2.1/255.255.255.0 cannot be used on interface net3

### ISSUE THREAD

**Issue by linjun61** [jclehner/nmrpflash#78]
I input  nmrpflash.exe -i net3 -a 192.168.2.1 -f .\RAX80-V1.0.3.106_1.0.50.chk
Address 192.168.2.1/255.255.255.0 cannot be used on interface net3.HOW to fix it?

**Comment by jclehner** [comment]
What's the output of `nmrpflash.exe -L`? In order to be able to use  `-a 192.168.2.1`, you'll have to configure `net3` to use an address from the same subnet (such as `192.168.2.2`). Usually, you shouldn't have to specify this, i.e. just use

```
nmrpflash.exe -i net3 -f .\RAX80-V1.0.3.106_1.0.50.chk
```

or, if that doesn't work, try

```
 nmrpflash.exe -i net3 -a 192.168.2.1 -A 192.168.2.2 -f .\RAX80-V1.0.3.106_1.0.50.chk
```
