### ISSUE TITLE
Trying to use this on a different Sercomm device - 0x8888

### ISSUE THREAD

**Issue by kar200** [jclehner/nmrpflash#80]
Hi,

Sorry this is not an issue with the software but it is the only place to try and get help. I have a Sercomm device (S3) and it seems that it uses a similar protocol for recovery. The difference is that it uses 0x8888 packets instead of 0x0912.

I am not good with C (or not at all with programming :)) so I am using scapy to craft packets and see what gets accepted. So far I have not gone far except finding out what wipes the whole flash drive (still keeps uboot and the important stuff).

If I send a packet with 0x01 at the start it erases the flash drive and then I beleive waits for what comes next. It has a timer and once time is up it reverts back to the first mode.

What I used for scapy. Please note sending only "01" does work to trigger the deletion and the timer (I guess waiting for the next request)

````
import codecs
d= '0`0000000000000000000000000044444b00'
data = codecs.decode(d, 'hex')
sendp(x = Ether(type=0x8888,dst='ff:ff:ff:ff:ff:ff')/Raw(load=pck_del), iface='enp6s0')
````

(below is the console output. I have removed all the lines from ranand_erase and only kept the first 2 and the last one)
````
DEBUG_DBG:state, listening
DEBUG_DBG:event, get version
DEBUG_DBG:state, listening
DEBUG_DBG:event, assign / set erase mode / console break
DEBUG_DBG:state, erase
DEBUG_DBG:event, set erase mode
DEBUG_INF:normal upgrade.
ranand_erase: start:300000, len:20000 
.ranand_erase: start:320000, len:20000 
.ranand_erase: start:7f60000, len:20000 
.DEBUG_INF:Erase Done.
DEBUG_INF:Program Starting.
DEBUG_DBG:sc_dl_fsm_steps 760 set(restart) time-out timer
DEBUG_INF:Erase Using: 7s
DEBUG_DBG:state prog; event, verify/console break/time-out
DEBUG_DBG:state, listening
DEBUG_DBG:event, time-out
````
I am attaching a wireshark dump as well. Please note that I only sent random packages created trying to change the first 2 bytes first since it seems that it trigeers the upgrade process.

[test1.zip](https://github.com/jclehner/nmrpflash/files/6715805/test1.zip)

If anyone can share a full upgrade process pcap that would be helpful to see if this can be done as well for these devices.

**Comment by kar200** [comment]
Just to add that I managed to brick my router by deleting the bootloader with sending "01" then followed by "05". Until I recover it I would close this for the moment.

**Comment by jclehner** [comment]
That sucks :( Do you happen to have a flash dump? I might take a stab at reverse engineering the bootloader, if I find the time, but I couldn't find any dumps online!

**Comment by kar200** [comment]
Sure. The device is not very popular that's why hhh.

The more popular one is the Beeline Turbo+ (on 4pda in russian since it's sold there).

[mtd0.zip](https://github.com/jclehner/nmrpflash/files/6720250/mtd0.zip)

Have fun!. I am trying to buy another one second hand. If you don't mind can you share any pcap you have about the upgrade process please?

**Comment by MaxS0niX** [comment]
If it helps:
[mtd0.gz](https://github.com/jclehner/nmrpflash/files/6720311/mtd0.gz)
After the command - saveenv
[mtd0.bt1.bin.gz](https://github.com/jclehner/nmrpflash/files/6720312/mtd0.bt1.bin.gz)
This is from the Beeline SmartBox Turbo+.

**Comment by kar200** [comment]
Hi @jclehner ,

Sorry not pushing or anything but I managed to get another device. I was wondering if you could share a sample of the already known commands for nrmpflash on the Netgear devices (or have a sample pcap with you).

I will try not to erase the router again lol.

**Comment by jclehner** [comment]
From what you describe, and the python sample you've provided, the two protocols don't really appear to have much in common. 

The NMRP protocol is described [here](http://www.chubb.wattle.id.au/PeterChubb/nmrp.html), but it doesn't use commands like the ones you've mentioned.

**Comment by kar200** [comment]
Just updating this in case someone else has a sercomm device. This seems to work although I have not been able to make it flash correctly my router yet. 

https://github.com/danitool/sercomm-recovery
