### ISSUE TITLE
rtnl_addr_add: Unspecific failure

### ISSUE THREAD

**Issue by mjknight50** [jclehner/nmrpflash#82]
I ran this once and it looked good:

```
❯ sudo ./nmrpflash -i enp0s31f6 -f tomato-R7000-1.28.AT-ARM-3.5-140-initial-64K.chk

Advertising NMRP server on enp0s31f6 ... -
Received TFTP_UL_REQ while waiting for CONF_REQ!
Received upload request without filename.
Uploading tomato-R7000-1.28.AT-ARM-3.5-140-initial-64K.chk ... OK (6852666 b)
Waiting for remote to respond.
Received keep-alive request (6).  
Remote finished. Closing connection.
Reboot your device now.
```

After reboot, the router is just cycling over and over.

When trying to run it again, I get:

```
sudo ./nmrpflash -i enp0s31f6 -f tomato-R7000-1.28.AT-ARM-3.5-140-initial-64K.chk -vv

Waiting for Ethernet connection.
Adding 10.164.183.253 to interface enp0s31f6.
rtnl_addr_add: Unspecific failure
```

To add more:

```
./nmrpflash -L
wlp2s0           192.168.43.68    9c:da:3e:9f:d4:1d
enp0s31f6        10.164.183.253   a4:4c:c8:57:6d:1d
docker0          172.17.0.1       02:42:9d:bb:5a:70
```

I fear that I now have a brick.  Any advice?

**Comment by jclehner** [comment]
It looks like `nmrpflash` failed to clean up properly, as the Ethernet interface shouldn't have kept its `10.164...` address!

Try resetting the interface using
```
# ip link set dev enp0s31f6 down
# ip link set dev enp0s31f6 up
```

If the device reaponds again, try leaving it on for some time after you get the `Remote finished. Closing connection.` message. Its possible that the device ends the NMRP session while flashing is still in progress!
