### ISSUE TITLE
nmrpflash No response

### ISSUE THREAD

**Issue by causlayer** [jclehner/nmrpflash#83]
```
-> % nmrpflash -L
en0              192.168.1.103    78:4f:43:8d:b0:47
p2p0             0.0.0.0          0a:4f:43:8d:b0:47
awdl0            0.0.0.0          62:04:fd:ad:5e:e0
llw0             0.0.0.0          62:04:fd:ad:5e:e0
en5              0.0.0.0          ac:de:48:00:11:22
en10             192.168.15.2     88:d7:f6:db:bd:8e
bridge0          0.0.0.0          82:dc:88:41:44:00
en1              0.0.0.0          82:dc:88:41:44:00
en2              0.0.0.0          82:dc:88:41:44:04
en3              0.0.0.0          82:dc:88:41:44:01
en4              0.0.0.0          82:dc:88:41:44:05
sudo nmrpflash -i en10 -a 192.168.15.1 -f /Users/slayer/Downloads/R6220_V1.1.0.106_1.0.1.img
Advertising NMRP server on en10 ... -
No response after 60 seconds. Bailing out.
```

macOS Big Sur 11.5.2,netgear R6260

**Comment by jclehner** [comment]
Are you 100% sure that `en10` is your Ethernet interface? What's `en1` or `en5`?

**Comment by causlayer** [comment]
Of course, I am sure it is en10, because I installed parallels,And I brushed x-wrt, the default address is 192.168.15.1.

**Comment by jclehner** [comment]
I don't see the "Waiting for Ethernet connection." message, so I'm assuming the device is already running before you started `nmrpflash` - which would explain your issue. Did you follow the steps as outlined in the readme?

**Comment by causlayer** [comment]
I have used the official application to restore the firmware, and now I cannot reproduce the problem you mentioned.
