### ISSUE TITLE
TFTP block rollover. Upload might fail!

### ISSUE THREAD

**Issue by crazyRM** [jclehner/nmrpflash#84]
**Hey!** so I get the error

TFTP block rollover. Upload might fail!

what I know is there bc the default max is 32mb but cant be bypassed using other TFTP programs but how would I do this with your program as I have a RBR50 router but the file size if 44.5Mb and I need to upload this version as it wont use the smaller version bc there is a higher update file but the file is corrupted bc it 44.5Mb and over the 32mb limit so its basically bricked

please let me know ASAP as I am basically without wifi and cant spend 1.5k getting a new house system

**Comment by jclehner** [comment]
If the device's NMRP implementation doesn't handle the TFTP block rollover correctly, there's no way to flash a larger image  using `nmrpflash`, unfortunately (nor with any other TFTP program).

The last version that was under the 32 MiB limit was `2.1.4.16`. I've created an image which contains this firmware, but presents itself as `2.7.3.22`. Note that downgrading the firmware might not work as expected, or even brick things further, **so flash this at your own risk**! The link is [here](https://drive.google.com/file/d/1ZTl3uN1YefDlbkvF3IknwjifblIRfD2a/view?usp=sharing).

If that still doesn't work, you'll have to open the device, and try debricking it via serial console.

**Comment by crazyRM** [comment]
ok thx i will test it now and btw do i leave the -fake or remove it?

**Comment by crazyRM** [comment]
hope turns out my router is fully bricked cant even rest it or anything just gonna have to buy a new one
