### ISSUE TITLE
Failed to add IP address (state=3).

### ISSUE THREAD

**Issue by esheyw** [jclehner/nmrpflash#85]
I'm trying to get stock firmware back onto an ac2600. I get this error when I try and run nmrpflash. I can't find any info about this error. Help? 

https://i.imgur.com/s2rkWM2.png screenshot of output. Run from powershell, as administrator.

**Comment by jclehner** [comment]
Please try this version, and report back:

[nmrpflash-0.9.16-4-g8aa77a3-win32.zip](https://github.com/jclehner/nmrpflash/files/7257740/nmrpflash-0.9.16-4-g8aa77a3-win32.zip)

**Comment by esheyw** [comment]
hey, thanks for the response, unfortunately I've lost access to the device -- was trying to get stock firmware back on it before I returned it, left it too late, now it's in the mail and is netgear's problem. Sorry I can't help test.

**Comment by jclehner** [comment]
Okay, closing this now. I'll leave the potential fix in the code for now, in case it happens to anyone else!
