### ISSUE TITLE
R6220, -L not returning correct network interface.

### ISSUE THREAD

**Issue by Cowbeardennis** [jclehner/nmrpflash#87]
Using -L only returns 
`net8   0.0.0.0          04:92:26:c2:46:65  (Ethernet)
Press any key to exit` 

Same output on both Lan1 and WAN on my router.

I do not know how to get the correct network interface for my router.

**Comment by jclehner** [comment]
Do you have more than one network interface?

If yes, try running `nmrpflash -vvL`, and post the output.  If not, then `net8` is the correct one.

**Comment by Cowbeardennis** [comment]
I have disabled all other interfaces except for my ethernet one.
-vvL returns
 `\Device\NPF_{1644D35E-2F6E-484B-A6F0-369758D21759}  (not an ethernet device)
\Device\NPF_{CC9C8DDC-A7EB-4141-AD40-1FC614E944C2}  (not an ethernet device)
\Device\NPF_{9C6F4D39-51DF-47E4-B9EC-549A76A93527}  (not an ethernet device)
\Device\NPF_{41752C21-4826-4C7B-B7D4-54FAB92D19AA}  100.64.229.112   04:92:26:c2:46:65  (Ethernet)
\Device\NPF_Loopback  (loopback device)
Press any key to exit`

 `nmrpflash -L` now returns `net7   10.164.183.253   04:92:26:c2:46:65  (Ethernet)`

trying to flash net7 gives me `Waiting for Ethernet connection.
Failed to add IP address (state=3).`
