### ISSUE TITLE
SRR60 - Timeout while waiting for ACK(0)/OACK.

### ISSUE THREAD

**Issue by stephlaf** [jclehner/nmrpflash#88]
Hi,

After trying everything I could find online and in the issues here, I'm reaching out to you.

McBook Air M1 2020, Big Sur

By the way, I have tried with multiple versions of the firmware `.img` files, and for all of them, when I tried to open them, it gives me this message: 
<img width="357" alt="Screen Shot 2021-12-09 at 16 31 09" src="https://user-images.githubusercontent.com/37821714/145478786-e23a1d94-d802-4b50-bac3-fea731be792f.png">

Here are the outputs of my attempts:

```
➜  Desktop ./nmrpflash -L
en0              192.168.2.121    1c:91:80:b9:41:ca
awdl0            0.0.0.0          ea:50:70:88:02:94
llw0             0.0.0.0          ea:50:70:88:02:94
ap1              0.0.0.0          3e:91:80:b9:41:ca
en5              192.168.1.10     a0:ce:c8:e2:1a:0b
anpi0            0.0.0.0          1e:00:d9:0a:99:58
bridge0          0.0.0.0          36:9a:40:09:13:00
anpi1            0.0.0.0          1e:00:d9:0a:99:59
en1              0.0.0.0          36:9a:40:09:13:00
en2              0.0.0.0          36:9a:40:09:13:04
en3              0.0.0.0          1e:00:d9:0a:99:38
en4              0.0.0.0          1e:00:d9:0a:99:39
```

```
➜  Desktop ifconfig en5
en5: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=6467<RXCSUM,TXCSUM,VLAN_MTU,TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether a0:ce:c8:e2:1a:0b 
	inet 10.164.183.253 netmask 0xffffff00 broadcast 10.164.183.255
	inet6 fe80::d5:d927:e91d:d835%en5 prefixlen 64 secured scopeid 0x13 
	inet 169.254.130.38 netmask 0xffff0000 broadcast 169.254.255.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
```
```
➜  Desktop sudo ./nmrpflash -i en5 -F firmware -f SRR60-V2.4.2.106.img -vvv -t 8000
Password:
Waiting for Ethernet connection.
Adding 10.164.183.253 to interface en5.
Advertising NMRP server on en5 ... /
delete: cannot locate 10.164.183.252
Received configuration request from 00:00:00:00:00:00.
Sending configuration: 10.164.183.252/24.
Received upload request: filename 'firmware'.
Using remote filename 'firmware'.
Uploading SRR60-V2.4.2.106.img ... << WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
<< WRQ(firmware, octet)
Timeout while waiting for ACK(0)/OACK.
```
If there is anything else you need, let me know. Thanks 🙏🏻

**Comment by jclehner** [comment]
Please try running it with `-a 192.168.1.1 -A 192.168.1.10`, which overrides the IP addresses used.

> By the way, I have tried with multiple versions of the firmware .img files, and for all of them, when I tried to open them, it gives me this message:

That's completely normal!

**Comment by stephlaf** [comment]
Thanks for the follow up. However, I did not have time to try this, since we managed to have the unit replaced.

**Comment by jclehner** [comment]
Okay, closing this now.

**Comment by user211120** [comment]
I know you have closed this Issue but I believe I have a very similar problem and I used your suggestion:

"Please try running it with -a 192.168.1.1 -A 192.168.1.10, which overrides the IP addresses used."

Apparently, I either issued the wrong command or in the wrong sequence.

It is Returning "rtnl_neigh_delete: Object not found" After "Advertising NMRP server"

I would appreciate it if you would tell me how to proceed (Append to This or Open New Issue).

Additionally, it looks like nmrpflash can be installed Directly on Ubuntu 22.04.3 lts with command:

sudo apt install nmrpflash

And I Do Not think I have a Firewall Active "Timeout while waiting for ACK(0)/OACK."

Thank you,
Noob Jim
