### ISSUE TITLE
keeps getting "Received keep-alive request" after uploading the firmware (R6220)

### ISSUE THREAD

**Issue by atkdef** [jclehner/nmrpflash#9]
The router is supposed to close the connection when it's done, but it keeps sending keep-alive request and the uploaded firmware seems to not be installed. 

```
nmrpflash.exe -i "net4" -f "d:\R6220-V1.1.0.64_1.0.1.img"
Advertising NMRP server on net4 ... -
Received configuration request from **:**:**:**:**:**.
Sending configuration: 10.164.183.252, netmask 255.255.255.0.
Received upload request without filename.
Uploading R6220-V1.1.0.64_1.0.1.img ... OK
Waiting for remote to respond.
Received keep-alive request.
Received keep-alive request.
Received keep-alive request.
...
```

Thanks in advance for any tips and help.

**Comment by jclehner** [comment]
A few possible scenarios come to mind:

* It keeps sending keep-alive requests until the firmware has actually been flashed. 
Any changes in LED patterns? For how long did you try before restarting?

* The upload succeeds, but the file is not accepted for some reason, and it waits for
another file upload. Maybe wrong remote filename? Does  `-R firmware` change anything?

In any case, please re-run with `-vv` and post the output. A `tcpdump` of the whole session
could really help in identfying this issue!

**Comment by atkdef** [comment]
@jclehner 

Thank you for your tips. 

After receiving 235 keep-alive requests it finally closed the connection and the firmware had been flashed into the router without any problem. I was probably too nervous and lack of patience when the router got bricked. Thanks for your suggestion, it's working again!

**Comment by jclehner** [comment]
Thanks for the feedback! I'll add that to the FAQ!

**Comment by ScottBeeson** [comment]
Glad I found this post before panicking. Can this be added to the "Common Issues" at the bottom of hte readme?

**Comment by jclehner** [comment]
> Can this be added to the "Common Issues" at the bottom of hte readme?

Done!
