### ISSUE TITLE
Success on Netgear WNDR4500v3

### ISSUE THREAD

**Issue by j1mw3b** [jclehner/nmrpflash#91]
Just to let you know that I successfully unbricked my NG router and then installed OpenWrt on it; although still don't know how it got bricked.

On a side note, I was having much difficulty getting nmrpflash to upload the firmware; just couldn't get it  going.  Even tried "blind" mode, which ran almost forever doing pretty much nothing.  I finally found a post that said start nmrpflash, and pushing reset for 10 seconds after power on.  Still nothing.  Then just pushed off/on button and nmrpflash worked!!
Actually the side note is that I started to try to compile nmrpflash and had some trouble getting all the dependencies, but it finally compiled.  Funny, it compiled on Linux Mint 20.2 (Ubuntu 20.04), but not on Mint 19.3 (Ubuntue 18.04LTS).  But your latest version works on both. 
Mint 19.3 does not have PCAP_IF_WIRELESS defined in /usr/include/pcap/pcap.h.

But anyway, again thanks.

**Comment by jclehner** [comment]
Thanks, updated the readme.
