### ISSUE TITLE
nmrpflash seems to fail when assigning mac address or ip in OS X 12.2 (21D49)

### ISSUE THREAD

**Issue by tnine** [jclehner/nmrpflash#92]
Hello!
  Unfortunately I have 2 bricked RBS850 Satellites. I'm attempting to use `nmrpflash` as described in the readme, and I experience the following error. 

```
➜  Downloads sudo ./nmrpflash -vvv -i en5 -f ~/Downloads/RBS850-V4.6.3.16/RBS850-V4.6.3.16-signed.chk
Waiting for Ethernet connection.
Adding 10.164.183.253 to interface en5.
ioctl(SIOCAIFADDR: Device not configured
```

I am attempting to flash my RBS from a MacBook Pro (16-inch, 2019), with a USB C attached 1G ethernet port.  Please let me know any additional information I can provide.  I'm a software engineer, and while this is not my area of expertise, I'm happy to contribute what I can to help in the diagnosis of the issue. 

While not the same issue at on the surface, it seems there is some issue with mac address spoofing in OS X on 12.2.  https://developer.apple.com/forums/thread/684745

Note that after this error, my interface no longer appears in the list.  Unplugging and re-plugging the device re-activates the network interface.

Before Error:
```
en0              10.10.0.27       88:66:5a:27:9a:f0
awdl0            0.0.0.0          26:3d:9b:0f:4f:96
llw0             0.0.0.0          26:3d:9b:0f:4f:96
en5              0.0.0.0          00:e0:4c:ac:f4:5f
bridge0          0.0.0.0          82:20:dd:62:54:01
en1              0.0.0.0          82:20:dd:62:54:01
en2              0.0.0.0          82:20:dd:62:54:00
en3              0.0.0.0          82:20:dd:62:54:05
en4              0.0.0.0          82:20:dd:62:54:04
ap1              0.0.0.0          aa:66:5a:27:9a:f0
```

After Error:
```
en0              10.10.0.27       88:66:5a:27:9a:f0
awdl0            0.0.0.0          26:3d:9b:0f:4f:96
llw0             0.0.0.0          26:3d:9b:0f:4f:96
bridge0          0.0.0.0          82:20:dd:62:54:01
en1              0.0.0.0          82:20:dd:62:54:01
en2              0.0.0.0          82:20:dd:62:54:00
en3              0.0.0.0          82:20:dd:62:54:05
en4              0.0.0.0          82:20:dd:62:54:04
ap1              0.0.0.0          aa:66:5a:27:9a:f0
```

**Comment by e38BimmerFN** [comment]
Check the flash program against working hardware to see if the app connects properly first. There maybe hardware problems at your devices that are in a bad state and thus causing connection problems.

**Comment by jclehner** [comment]
The issue occurs when assigning the IP address - `nmrpflash` doesn't spoof the adapter's MAC address. Before running `nmrpflash`, try assigning a static IP address to `en5` using `ifconfig`. Does that work?

**Comment by tnine** [comment]
It perhaps might be a linking issue on a previous OSX build? I just built and installed it from the source, and I don't experience this issue.
