### ISSUE TITLE
Use nmrpflash over wifi

### ISSUE THREAD

**Issue by toastom** [jclehner/nmrpflash#95]
Is it possible to use this tool over a wireless connection to the router, rather than a wired connection like in the instructions? My Debian laptop doesn't have an ethernet port. If I understand right, the wireless connection to the device might go out in the middle of the firmware flashing process, which could potentially truly brick the router lol. I want to use this tool to get around Netgear's restriction on flashing third-party firmware and install OpenWRT.

If this assumption is right and a wired connection is mandatory, I do have another Windows laptop that has an ethernet port on it. The only problem with this is that I tried to run the program and I was not able to input any command-line arguments, and Windows couldn't see my firmware.chk or the nmrpflash.exe.

Any help is appreciated. Thanks.

**Comment by toastom** [comment]
Well it turns out I didn't need to run it over wifi. I fixed the issue with Windows by first booting into a Live USB Linux Mint environment and running the program there. It works on my Netgear R7000P!

**Comment by jclehner** [comment]
For future reference: the connection to the router to be flashed has to be Ethernet. What could work though is if you plug the NETGEAR router into your Wi-Fi router, i.e.:

```
(nmrpflash)  <-----Wi-Fi------> (Wi-Fi router) <----- Ethernet ----->  (NETGEAR router)
```
