### ISSUE TITLE
Success in Fixing and Upgrading An AC3600 Nighthawk That Wouldnt Update

### ISSUE THREAD

**Issue by sissieadmin** [jclehner/nmrpflash#96]
I wanted to say thank you to the developers, and post my experience with this tool. I use Linux.

I had a Netgear AC3600 that wouldnt update. I actually have two Nighthawks that wouldnt update to newer firmware versions. I managed to fix one that I just bough cheap and second hand, the other has yet to be fixed and I will be trying soon. I found lots of threads of Netgears of this model or similar not upgrading.

The first was on a 1.4.1.50, and wouldnt upgrade to any revision normally. With nmrpflash it failed to upgrade to .84, the current latest, but it upgraded successfully to .68. One on .68 I was able to upgrade normally to .84.

I will try the second router that I have had for longer. I will likely forget to update this post, but I am anticipating similar results since the issue was almost exactly the same.

**Comment by sissieadmin** [comment]
I completed the upgrade for my other netgear router. This one was an AC4000 or R8000P.

This one required a timeout to be defined in the command to upgrade. I was able to upgrade from 1.4.1.50 to the latest 1.4.2.84 firmware using the following command (notice the -t and -T which I took from [here](https://github.com/jclehner/nmrpflash/blob/master/README-R7000.md)):

> sudo ./nmrpflash -i ens7 -f R8000P-V1.4.2.84_1.3.42.chk -t 10000 -T 10000
> Advertising NMRP server on ens7 ... |
> Received configuration request from 10:0c:6b:1a:85:e2.
> Sending configuration: 10.164.183.252/24.
> Received upload request without filename.
> Uploading R8000P-V1.4.2.84_1.3.42.chk ... Warning: TFTP block rollover. Upload might fail!
> OK (53477454 b)
> Waiting for remote to respond.
> Remote finished. Closing connection.
> Reboot your device now.
>

**Comment by jclehner** [comment]
Do you remember how much time it took to flash the R8000P? You specified a timeout of 10000 seconds (2h, 46 min, 40 s), whereas the default is 15 minutes (I'd like to increase that in the next release - would 30 minutes be enough?).

**Comment by jclehner** [comment]
Thanks, updated the readme. BTW `-t 10000` is now the default in the newest release. `-T` is still at 15 minutes.
