### ISSUE TITLE
NMRP process not found with RAX40v2

### ISSUE THREAD

**Issue by WraithBand** [jclehner/nmrpflash#98]
Hi
I've tried to flash a RAX40v2 using the latest version (0.9.16) but it doesnt seem to support this router.

After executing a command :
nmrpflash.exe -R WW -f RAX40v2-V1.0.3.96_2.0.59.chk -i net8
I have the "No response after 60 seconds. Bailing out." error.

Same using the blind mode. Nothing seems to happen although I already did it with a RAX40v1 (same ethernet configuration) and it worked perectly.

**Comment by jclehner** [comment]
Did you turn off the router before executing `nmrpflash.exe`?

**Comment by WraithBand** [comment]
Yes I turn it off.

**Comment by jclehner** [comment]
Does the router boot up normally? And if not, do the LEDs light up? How did it get bricked (if it did)?

**Comment by WraithBand** [comment]
Yes it boots normally. I want to flash it to change region but everything is working fine ;)
Maybe the RAX40v2 has maybe a totaly different protocol compared to v1 ? Maybe that's why the NMRP doesn't work ?

**Comment by jclehner** [comment]
Does the attached version fix your issue?

[nmrpflash-0.9.17-4-g784536c-win32.zip](https://github.com/jclehner/nmrpflash/files/8926973/nmrpflash-0.9.17-4-g784536c-win32.zip)

**Comment by WraithBand** [comment]
I also give you my network interface parameters (inet7 = Eth2) : 

```
Carte Ethernet Ethernet 2 :

   Suffixe DNS propre à la connexion. . . :
   Description. . . . . . . . . . . . . . : Intel(R) Ethernet Controller (2) I225-V
   Adresse physique . . . . . . . . . . . : 24-4B-FE-DD-F6-F1
   DHCP activé. . . . . . . . . . . . . . : Non
   Configuration automatique activée. . . : Oui
   Adresse IPv6 de liaison locale. . . . .: fe80::4158:149d:8f48:5292%7(préféré)
   Adresse IPv4. . . . . . . . . . . . . .: 192.168.1.10(préféré)
   Masque de sous-réseau. . . . . . . . . : 255.255.255.0
   Passerelle par défaut. . . . . . . . . : 192.168.1.1
   IAID DHCPv6 . . . . . . . . . . . : 136596478
   DUID de client DHCPv6. . . . . . . . : 00-01-00-01-29-0A-F6-5B-24-4B-FE-DD-F6-F1
   Serveurs DNS. . .  . . . . . . . . . . : 8.8.8.8
   NetBIOS sur Tcpip. . . . . . . . . . . : Activé
```

**Comment by WraithBand** [comment]
Hey 
[jclehner](https://github.com/jclehner)
I'm sure you are very busy :)
Just to let you know that if you want me to test something else or give you more info I'm free to do it ;)
Have a nice day,

**Comment by jclehner** [comment]
Try using the `-m` option to manually specify the router's MAC address. 

If that doesn't work, you could also try blind mode (`-B`) as a last resort.

**Comment by WraithBand** [comment]
The topic can be closed.
